### ISSUE TITLE
CloudShell Article Link

### ISSUE THREAD

**Issue by rferina** [FredHutch/wiki#1002]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/scicomputing/compute_cloud/

### Specific information requests or concerns, or specific region on page of content to refresh.
I don't think the article 'CloudShell at Fred Hutch' exists, despite sciwiki saying it should be available after February 2023. The link should be updated if the article does exist, or updated with a new timeframe if it is expected to be written.

**Comment by laderast** [comment]
Further research needed

**Comment by laderast** [comment]
Remove Feb 2023 mention
