### ISSUE TITLE
Broken link to hpc temp storage page

### ISSUE THREAD

**Issue by chrisequalsdev** [FredHutch/wiki#1016]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/store_scratch/

### Specific information requests or concerns, or specific region on page of content to refresh.

Link to page containing info about hpc/temp storage platform is not working

**Comment by thackwelFH** [comment]
Link fixed: https://github.com/FredHutch/wiki/pull/1017
