### ISSUE TITLE
New Computing Grant Boilerplate materials

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#103]
**Proposed Domain**
Computing domain for the new markdown, and a link to the content in generation/study_proposal

**Content Summary**
Scicomp oriented overview of resources available for putting into a grant application.  Make it an overview of things that don't change super often, and then put at the top of the page:
> Please contact `scicomp` for additional detail about current offerings.

**Comment by dirkpetersen** [comment]
done

**Comment by vortexing** [comment]
Where are the links to it?
