### ISSUE TITLE
Shared Resources PI directory permissions notice

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#1033]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://github.com/FredHutch/wiki/blob/main/_scicomputing/store_posix.md#special-note-for-shared-resources-genomics-data

### Specific information requests or concerns, or specific region on page of content to refresh.

Need to add discussion of permissions in the PI's SR directory- add notice that changing permissions here will interrupt data delivery from SR and Genomics.

### @ GitHub username of the listed primary reviewer of the page if known

requested by @jnyhuis , @FredHutch/scicomp authors

**Comment by laderast** [comment]
@jnyhuis Can you give more details about what we need here?

**Comment by atombaby** [comment]
From the ticket:

> https://sciwiki.fredhutch.org/scicomputing/store_posix/
> *This is based off of ticket #SC00014960
> 
> Please add the following sentence (or a similar one) to the section "Fast" in the following area:
> 
> "Additionally, links to other data sources can appear here, such as data from the Fred Hutch Genomics Shared Resource (/SR). Changing ownership or permissions of the ./SR folder tree will break the automated delivery of scientific data to these folders. We ask that you do not change the ownership or permissions of the ./SR folder tree."
