### ISSUE TITLE
Broken link to Openscapes Home Page

### ISSUE THREAD

**Issue by tefirman** [FredHutch/wiki#1042]
**URL of page(s) of concern**
https://hutchdatascience.org/openscapes/

**Describe the problem**
Not urgent, but the link to the Openscapes home page at the top of the page linked above is incorrectly formatted and produces a "Page Not Found" error.

**Comment by laderast** [comment]
@tefirman - I was confused by this and then I realized this is on the hutchdatascience.org page - I'll open an issue over there.
