### ISSUE TITLE
FHCC to Fred hutch

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#1048]
**URL of page(s) of concern**

FHCC Patient Clinical Data for Research” wiki page, and for any other mentions on the Wiki, can mentions of “FHCC” please be updated to “Fred Hutch” or “Fred Hutch Cancer Center”.
 

**Describe the problem**
Brand alignment!!

**Comment by laderast** [comment]
This is being fixed in https://github.com/FredHutch/wiki/pull/1074
