### ISSUE TITLE
R module request

### ISSUE THREAD

**Issue by pmorzywolek** [FredHutch/wiki#1070]
Hello,

not sure whether it is a proper channel for such a request, but would it be possible to add R module "bartMachine" to fhR-4.4.0-foss-2023b?

Best regards,
Pawel

**Comment by atombaby** [comment]
Please email module requests to _scicomp_. It's the best way to get help with modules, rhino/gizmo, and other scicomp supported resources.

 - Michael

**Comment by pmorzywolek** [comment]
Thank you!
