### ISSUE TITLE
broken links to WILDS docker repo

### ISSUE THREAD

**Issue by jayoung** [FredHutch/wiki#1071]
URL of page of concern:  https://sciwiki.fredhutch.org/dasldemos/computational_rank/

The two links to WILDS are both broken. 

Here's one in context:

Before reinventing the wheel, check out the [WILDS Docker Repository](https://getwilds.org/packages.html#docker) to see if there’s a similar workflow to what you need. You may just need to [fork an existing workflow](https://getwilds.org/packages.html#wdls) (make your own version) to get started.

and here's the other:
This assumes that nothing similar exists in [WILDS WDL Workflows](https://getwilds.org/packages.html#wdls). If something does, then fork that workflow and start from there.

thanks!

**Comment by laderast** [comment]
@jayoung - we're fixing this in a pull request. Thanks for letting us know.
