### ISSUE TITLE
Library of Interesting Slurm Commands

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#120]
**Proposed Domain**
Bioinformatics

**Content Summary**
A list of interesting slurm commands commonly used (or searched for) by bioinformatics staff using the local cluster and examples of when they use them.  

**Local Content Expert(s)**
Chao-Jen, Jenny Zhang, Jenny Smith

Include links:
https://slurm.schedmd.com/
To Computing's Linux section

**Comment by atombaby** [comment]
I've started in on this- look in the branch https://github.com/FredHutch/wiki/tree/mrg/computing/cluster_usingSlurm

**Comment by vortexing** [comment]
WHOOPS!!!!  CRAP!
