### ISSUE TITLE
lunr search index concatenates words on either side of a newline

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#121]
**URL of page(s) of concern**
Specify the URLs of the page(s) where there are technical problems.

All pages (problem is with search functionality)

This is really just a placeholder for me to come back to this issue since I don't have time to fix it right now. 

**Describe problem**

If you have some html like this:

```
<p>
frumious
Bandersnatch
</p>

```

jekyll will put the string `frumiousBandersnatch` in the [search index](http://sciwiki.fredhutch.org/assets/js/lunr/lunr-store.js). 

So then if you try and search for `bandersnatch` it will not be found. 

If you start typing `frumiousBandersnatch` you will get a result.

For an actual example on our wiki, try searching for `atotally`. This will bring up the Docker page, but that string does not occur there. You will find `a totally` and if you view source you'll see those two words are separated by a newline.

This is not our issue to fix (unless we want to contribute a fix upstream), but we need to figure out which Ruby package is generating the index so that we can report the bug or see if anyone else has reported it. Haven't been able to find it yet.

**Comment by bmcgough** [comment]
The theme is building the lunr_store.js file using Liquid. It uses `strip_newlines` and `replace` along with `strip_html` to render the page excerpt into simple text. It is `strip_newlines` that removes `/r?/n` from the string. Two options. Liquid has also `newline_to_br` that replaces `\n` with `<br />\n` (note that it does nothing with `\r`). So we could modify the Liquid the theme uses to do `newline_to_br` and then `replace` `<br />` with [space] and then `strip_newlines`.

I will look at making an issue upstream to see if we can get this fixed. This is clearly unintended and broken.

**Comment by dtenenba** [comment]
Thanks! If you make an issue upstream please link to it here....

**Comment by bmcgough** [comment]
https://github.com/mmistakes/minimal-mistakes/issues/1883

**Comment by dtenenba** [comment]
This appears to be fixed now. Searching for `atotally` no longer works; searching for `totally` brings up many pages including the Docker page; and `atotally` no longer appears in the index.

**Comment by vortexing** [comment]
Who used the word totally?????  (thanks BTW)

**Comment by dtenenba** [comment]
Sam, apparently.
https://github.com/FredHutch/wiki/commit/dd74e27e7fd244dc11edf4ddec1d43eb7be94caf

**Comment by vortexing** [comment]
That's what that "blame" button should be for.  Totally.  ;)
