### ISSUE TITLE
STorage for Collaboration alternate approach

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#124]
**URL of page(s) of concern**
http://sciwiki.fredhutch.org/computing/store_collaboration/

**Describe problem**
It seems that now that the object store section has been built up (or is in the process of being built up), the content about S3 in the collaboration section seems a bit redundent or like it should be incorporated into the other documentation. 

I think a decision as to what S3 is going to be for us is important here.  Yes, it is used for collaboration, but also for storage without collaboration.  Perhaps main content needs to be in objectstore, but then the specific examples of using S3 for collaboration should be in this file?  

More discussion/thought is needed.

**Comment by dirkpetersen** [comment]
I think we decided to remove S3 from collaborative storage even if it can be used for collaboration (like any storage can ) but it is not its strongest feature.

**Comment by vortexing** [comment]
Yup and we de-duplicated it too!!  This is done!
