### ISSUE TITLE
Check for orphaned images in assets folders

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#125]
At some point we will benefit from cleaning a bit by identifying images in asset folders that are not specifically included in any markdown.

An added bonus would be to identify images in asset folders which are NOT inside the individual asset folder where the markdown that uses that image is so that we could uncross the streams!

**Comment by atombaby** [comment]
```
for F in $(find assets/* -type f) ; do grep -r -q $F * || echo "$F  is orphaned"; done
```

If we feel confident that this works, the "or" condition can also execute `rm $F`

```
assets/2018-06-13-16-47-07.png  is orphaned
assets/2018-06-13-16-47-18.png  is orphaned
assets/css/main.scss  is orphaned
assets/screenshots/2018-09-27-11-22-50.png  is orphaned
assets/store_use_cyberduck/2018-07-19-10-56-28.png  is orphaned
assets/store_use_cyberduck/2018-07-19-10-56-49.png  is orphaned
assets/store_use_cyberduck/2018-07-19-10-57-05.png  is orphaned
```

**Comment by atombaby** [comment]
I can rewrite this for the Rakefile

**Comment by atombaby** [comment]
check branch https://github.com/FredHutch/wiki/tree/mrg/asset_orphans for updates

**Comment by vortexing** [comment]
@atombaby do you have any recollection of whether you incorporated some checking here?  Or does this imply that someone just occasionally needs to do the above on the repo?  If it's the latter, I will take care of it, but not if it's the former.  ;)

**Comment by vortexing** [comment]
Considering adding this process (excluding the css and js folders) to the build process so that when a merge into main occurs that creates an orphaned asset, it will:
- break the build
- file an issue and assign it to the person who did the PR/commit/merge or something, saying what the issue is.

Then folks can fix that and then remerge the PR.  
@dtenenba  is working on how that would happen in GitLab.
