### ISSUE TITLE
Resources and links for sharing data publicly

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#129]
**Proposed Domain**

Bioinformatics

**Content Summary**

I don't know if this would go in the existing [page](http://sciwiki.fredhutch.org/generation/human_shareDeposits/) about data sharing, but there seems to be a dearth of links to repositories and services for hosting data and the mechanisms for storing data in them.  For example, [figshare](https://figshare.com/) is one project set up for that.

**Local Content Expert(s)**

Don't know...

**Comment by sgglick** [comment]
No surprised.  I may have a partial list someplace....

**Comment by vortexing** [comment]
@atombaby neither @ptvan nor I really have a good idea of what exact example of this you are envisioning.  Both of us feel like some guidance for how to interact with public data sets would be great, but specifically sharing our own is not something we know much about.

**Comment by rbarfield** [comment]
For dbGAP,  I know some people who have uploaded data there recently. I can reach out and ask if they have links to the forms if we want to include those on the page? Public repositories I know of off top head GTEx, Roadmap, 1000 genomes, UK biobank, TCGA.

Are we suggesting just having a little link to some of these sites? I think some of these (such as GTEx) do involve having an IRB or data-use proposal in place which I'm not super familiar with. 

Doing a cursory search, I see two R packages [DeepBlueR](https://bioconductor.org/packages/release/bioc/vignettes/DeepBlueR/inst/doc/DeepBlueR.html) and [Biomartr](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5408848/) that could may be used for downloading epigenomics data, but I've never used them. 

Sorry, know this was maybe a dormant thread.

**Comment by sgglick** [comment]
Thanks for the comment.  Actually, I don't want to lose your thoughts. can you email directly at sgglick@fredhutch?  Thanks

**Comment by vortexing** [comment]
Yes, we should put in links and in  my experience, it'd be good to know if there are tools out there to help you actually ACCESS and make sense of public data sets or if someone has actual human advice about it.  

Another type of this is Bioconductor's AnnotationHub package.  
http://bioconductor.org/packages/release/bioc/html/AnnotationHub.html

I dream of this issue being addressed, it is not dead, just languishing.

**Comment by vortexing** [comment]
For advice on dbGAP submission:
https://sciwiki.fredhutch.org/generation/human_shareDeposits/

**Comment by vortexing** [comment]
for USING public data:
https://sciwiki.fredhutch.org/bioinformatics/dm_ingest/

**Comment by rbarfield** [comment]
Heard back from one person on dbGAP submission, they pointed me to these webpages


https://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/GetPdf.cgi?document_name=HowToSubmit.pdf
and
https://datascience.cancer.gov/data-sharing/submitting-data#expectations

I think the first one in particular looks good, though maybe good idea to add the pdf to the GitHub so don't lose it if link ever dies.

What do you think? Can add it to https://sciwiki.fredhutch.org/generation/human_shareDeposits/

**Comment by vortexing** [comment]
Added your two links to pull reqeust #286
