### ISSUE TITLE
Requesting resources via Slurm and node classes available

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#138]
**Proposed Domain**
Computing

**Content Summary**
Where doth one find the descriptions of resources for each node type these days (PS: Assume I cannot Sharepoint)?

**Local Content Expert(s)**
SciComp

**Comment by vortexing** [comment]
@bmcgough @atombaby Do we have a table for this yet?

**Comment by ptvan** [comment]
@vortexing @bmcgough This table from the SciComp wiki seems appropriate, if it is still accurate: https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Gizmo%20Cluster%20Quickstart.aspx

**Comment by atombaby** [comment]
The information is mostly accurate, though the local storage row needs some review.  I thought we were going to put this in a reusable form- something that could be plugged into many pages.

**Comment by vortexing** [comment]
@atombaby are we happy with the current state of this?  @bmcgough

**Comment by atombaby** [comment]
Also: the information is presented in [this page](https://sciwiki.fredhutch.org/scicomputing/compute_platforms/#resource-and-node-description-information)
