### ISSUE TITLE
Parallel Processing in R using local HPC resources

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#139]
**Proposed Domain**
Bioinformatics (or Computing, y'all can duke it out)

**Content Summary**
I have my Rscript using the `parallel` package and have the parallel portion of my process inside `mclapply`.  The script reads in the csv giving it instructions (451 of them in fact), loads/installs libraries (one is a github library), then tells mclapply to do go at it on the parallel jobs.

Now I want to just sbatch the task, how do I  request cluster nodes/cpus/tasks such that my one job that is set up to use multicores will ACTUALLY have multiple cores available for it.

**Local Content Expert(s)**
@atombaby @bmcgough Or perhaps someone regularly DOING parallel processing in R for bioinformatics?

**Comment by atombaby** [comment]
@vortexing this is a _great_ topic.  CPU management in general.  Whereabouts do you see this going?

**Comment by vortexing** [comment]
I can see approaches for parallelizing in R going in here: /bioinformatics/prog_R/

Then stuff about array jobs, and slurm-y things could go over here:  /computing/cluster_usingSlurm/ . Also the slurm-examples repo could be linked in that page as well.  

Are there other themes related to CPU management that you'd want to write up?

**Comment by vortexing** [comment]
I feel like we addressed this pretty ok now.  @ptvan @atombaby Thoughts??

**Comment by atombaby** [comment]
The resources on or indicated by the wiki are:

https://sciwiki.fredhutch.org/scicomputing/compute_parallel/
https://github.com/FredHutch/slurm-examples

The latter has a number of different samples for parallel R.
