### ISSUE TITLE
How do I know how much data a PI has stored and where?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#146]
**Proposed Domain**
Computing  - Possibly in the Data Storage Overview page with the table of storage locations @dirkpetersen is putting in
OR
Bioinformatics - Data Storage Best Practices  (where the preliminary markdown table of storage locations and allocations exists as an overview for researchers)

**Content Summary**
If there are ways to know how much data a group has and where it is in order to know how to better manage their overall digital assets, can we know about that?  

**Local Content Expert(s)**
@dirkpetersen or really anyone in SciComp

**Comment by ptvan** [comment]
I'm not sure if this should be a separate issue, but perhaps we should also mention the fact that all data is automatically backed up and (if I understand correctly) the max counts towards the quota at least as far as backup is concerned. Data Storage Best Practices should mention of `/scratch` and the retention schedules

**Comment by ptvan** [comment]
This is now addressed by https://sciwiki.fredhutch.org/computing/store_posix/
