### ISSUE TITLE
Whole Genome Sequencing Guidance tidbits

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#149]
**Proposed Domain**
Here: https://sciwiki.fredhutch.org/generation/datagen_dnaApproaches/#human-whole-genome-sequencing-wgs-guidance
In Generation

**Content Summary**
A couple of small tidbits are remaining in this page for @pattygalipeau  or someone from a lab that has experience with WGS to fill in.  They are marked in commented out text in the markdown.

**Local Content Expert(s)**
@pattygalipeau 
@kenjioman 
Others?

**Comment by pattygalipeau** [comment]
Reserving time for this Wed 12/11 to read through this and see where I can contribute or get help from others on this.

**Comment by vortexing** [comment]
@pattygalipeau Do you think you have any canned info you might be able to copy and paste for us about approaching whole genome sequencing projects that you've learned?

**Comment by vortexing** [comment]
Have We learned anything on this front since this?

**Comment by vortexing** [comment]
maybe but so many other things have changed.
