### ISSUE TITLE
Establish contact with Flow folks at Core

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#156]
A reminder from our meeting, introducing ourselves and what we're doing to get input from Flow folks and catch dirty data before it starts...

**Comment by jdberndt** [comment]
Perhaps this issue should be more broadly stated to include establishing on ramps to flow, proteomics and imaging core facilities?

**Comment by ptvan** [comment]
True, but I thought each of the cores could be a separate issue to be tracked/closed, assuming we don't get them done all simultaneously (which, admittedly, would be nice...)

**Comment by vortexing** [comment]
Yeah, they might move independently.  @jdberndt if you want to do the imaging part or proteomics, perhaps make an issue for each and assign them to yourself so we all know you're working on it?

I will work on carving out a space in Data Generation for other Shared Resource Core data types, and also ponder that Tidy Data section.  ;)

**Comment by vortexing** [comment]
Ain't gonna happen beyond what we have.
