### ISSUE TITLE
Guidelines for MAKING tidy data to keep your collaborators sane.

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#157]
**Proposed Domain**
Generation

**Content Summary**
We'd like to get a section in the sidebar for an introduction to what Tidy DAta is and what resources exist to give people some guidelines for different data types as to what Tidy might look like.  

**Local Content Expert(s)**
@ptvan and @vortexing should be able to tackle this one along with really anyone!!!

**Comment by ptvan** [comment]
I like this idea. I'll collect bits about general tidy data and stash it here, and we'll flesh it out as the specific "clean data" cores get more content.

**Comment by vortexing** [comment]
I'm going to close this for now, but at some point it'd be great to get some editor who's inspired to add to what Phu has.

**Comment by k8hertweck** [comment]
Can we keep this open? @Chilliwack and I had planned to assign as a milestone to one of the incoming wiki writers.

**Comment by vortexing** [comment]
Sounds great.  Are there incoming wiki writers?
