### ISSUE TITLE
Work with FH Cellular Imaging Core to establish on ramp

### ISSUE THREAD

**Issue by jdberndt** [FredHutch/wiki#158]
**Proposed Domain**
Data generation

**Content Summary**
https://sharedresources.fredhutch.org/core-facilities/cellular-imaging

**Local Content Expert(s)**
Julio Vasquez

**Comment by vortexing** [comment]
@pchatter26 will update this!!!

**Comment by vortexing** [comment]
Tabling this.  If someone wants it in the future, then we'll be glad to host their docs!
