### ISSUE TITLE
Work with Proteomics core to establish on ramp

### ISSUE THREAD

**Issue by jdberndt** [FredHutch/wiki#159]
**Proposed Domain**
Data Generation

**Content Summary**
https://sharedresources.fredhutch.org/core-facilities/proteomics

**Local Content Expert(s)**
Phil Gafken

**Comment by vortexing** [comment]
Hey @clin888 if you get a moment, it'd be great to get your input on this content!  @pchatter26 Is willing to help!!!

**Comment by vortexing** [comment]
Y'all can certainly revisit this later if it becomes more realistic.
