### ISSUE TITLE
Make wiki conventions more obvious to readers

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#160]
There are some communication with readers issues that I'd like to ponder/improve as we go:

- [ ] We have used the convention of putting usernames in `backticks` but we need to tell people more clearly now that that means you just add the @domain afterward

- [x] Make it more obvious that they can edit any page by clicking on the "Edit This Page" link - perhaps bring it up to the top of the pages?  or in the TOC on each page?

- [x] Make it more obvious how they can comment on or ask for new content by clicking on teh "Send us Comments" link - perhaps also bringing that along to the top OR put it in the TOC on each page?

**Comment by vortexing** [comment]
@ptvan and @jdberndt What do you think about me putting in a small chunk of html into the top of every content page just below the front matter so that all our pages would look like this drafts template:

https://sciwiki.fredhutch.org/drafts/contentTemplate/

Would that help with the second and third issues in this issue at all even if it's just a first pass?  Or should I wait for something more comprehensive?

**Comment by jdberndt** [comment]
Looks good to me other than I would prefer there be a little more whitespace after the word "Github"?

**Comment by vortexing** [comment]
Me too on the whitespace!!!  I tried a couple things but I forget my html!  

If I can fix the whitespace then I will endeavor to move this into the main site.

What do you guys think about changing the username convention from `username` to `username@`?  Does that make it more clear that it's the beginning of an email?  if you type that into your mail client, it'll likely autocorrect to the domain.

**Comment by ptvan** [comment]
I'm good with `username@`

**Comment by vortexing** [comment]
From another thread, it seems that bots can pick up the `username@` as well and knowing the domain of the site can slice/dice/spam. :(  So I think for now `username` will stay until any of us have another Big Idea.  I'll leave this issue open for now too.

**Comment by vortexing** [comment]
Let's give up on this for a while.
