### ISSUE TITLE
Privacy and Security page for Human subjects as missing link

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#168]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/generation/human_privacySecurity/

**Describe problem**
"Data/Information should be handled according to the FH Information Classification Standard, which requires security and handling standards commensurate with the risk of information mishandling. An easy to read chart is located HERE. "

HERE does not have a link!  Where is this pointing to?

**Comment by sgglick** [comment]
Such a chart does not exist on FH CenterNet. Moving communication to email

**Comment by sgglick** [comment]
Will insert a link to the standard as written.  There is no quick view/graphic representing the standard.

**Comment by sgglick** [comment]
There should eventually be an easy to read chart on the ISO site to which to link.  One does not exist now.

**Comment by vortexing** [comment]
Did this!
