### ISSUE TITLE
Pathways to bioinformatics

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#172]
**Proposed Domain**
Bioinformatics

**Content Summary**
What programming language should I learn?
What are use cases (and learner profiles) for different programming languages?
What programming languages are useful for different subdisciplines?

**Local Content Expert(s)**
Darn, I guess....me?

**Comment by vortexing** [comment]
ha!   I highly recommend doing the third item in this overview page:
https://sciwiki.fredhutch.org/bioinformatics/prog_overview/

And then the second item in the individual language pages in the prog_ section.  

All to the service of the first item.  Godspeed.  Also, new Wiki Writers-Editors can help!

**Comment by ptvan** [comment]
hello @k8hertweck ! My 2 cents is that an increasing number of people interested in getting into bioinformatics have heard of Go and/or Julia, and maybe some discussion of these would be nice, even if they end up not being the focus.

**Comment by vortexing** [comment]
What do you think @k8hertweck, do you have any beginnings of this or people in classes who are game to write their story?

**Comment by vortexing** [comment]
@k8hertweck this is still open as well.  What are your thoughts?  What are you seeing come up during your intro classes that could be addressed in doc form?

**Comment by k8hertweck** [comment]
Thanks for poking me about this, Amy. I've drafted some language but started second-guessing myself, but I'll go ahead and submit what I've got and we can keep going from there.

**Comment by vortexing** [comment]
Toss it in a branch and do a pull request and we can all weigh in and help out!

**Comment by vortexing** [comment]
Done by @iankirkman
