### ISSUE TITLE
Can people simply turn option to "Not Watching" for the AllFredHutch team to make this stop?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#177]
We'll see if people get spammed when they have the option set to Not Watching.

**Comment by vortexing** [comment]
It seems this might be the answer to all of our notifications.  An attempt will be made to adjust all of our preferences for the AllFredHutch to "Not Watching".  

We do apologize for the spam that has come from the Wiki repo because we currently are the only repo that has added the AllFredHutch team.

**Comment by ptvan** [comment]
Haven't heard more complaints about this lately, so assume fixed. Will revisit if additional complaints emerge.
