### ISSUE TITLE
Migrate "R Known issues" from SciComp wiki to /computing/cluster_software & overhaul ? 

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#187]
**Proposed Domain**
Computing

**Content Summary**
There's a useful "R issues on Rhino" page (https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/R%20Known%20Issues%20and%20Changes%20Omnibus.aspx) but AFAIK it's not linked anywhere. It's still being referenced/used (a postdoc in my lab found it this week), so maybe we can migrate it to https://sciwiki.fredhutch.org/computing/cluster_software/#packagesmodules-for-python-and-r and update with any additional changes ?

**Local Content Expert(s)**
Anyone in SciComp, really.

**Comment by vortexing** [comment]
That seems like it could go directly into a compdemo.  Can we do that?!??!?!  @fizwit You edited that page last.  What do you think?

**Comment by atombaby** [comment]
One thing to keep in mind is that we really don't have _transitory_ bugs since we keep old (i.e. buggy) versions of R around.  There are, of course, other issues that may be fixed within an EB release.  In the current page it's not clear which "bugs" apply to which releases.

**Comment by vortexing** [comment]
@bmcgough  and @atombaby  what do you guys think about this issue?  Can we resolve it in some way?  What portion of known bugs do we want to document for people?

**Comment by vortexing** [comment]
@ptvan do you think moving some of this content to your R Tips and Tricks demo might be of interest?

**Comment by ptvan** [comment]
That sounds good to me !

**Comment by vortexing** [comment]
@ptvan Shall we resolve this one way or the other?

**Comment by atombaby** [comment]
We're going to track build-specific information in the index for the build description (https://github.com/FredHutch/easybuild-life-sciences/issues/177)

**Comment by fizwit** [comment]
I see two types of R issues that can be documented. General issues that effect multiple versions of R and/or R issues relating to our environment.  And specific issues that would only relate to a single release.  To handle the case of documenting issues with a release, I have added an [Know Issues](https://fredhutch.github.io/easybuild-life-sciences/r/R-3.6.0-foss-2016b-fh1/)
 section of the software release docs in Easybuild life sciences. 

More general issues with R could be documented here [Available R Modules](https://fredhutch.github.io/easybuild-life-sciences/r/)

My suggestion moves software issues out of SciWiki and puts them with the software documentation. 
[Scientific Software](https://fredhutch.github.io/easybuild-life-sciences/)

The applies to Python and other tools.

**Comment by vortexing** [comment]
I think this is good.  I like @fizwit 's solution. I'm calling it!!!!
