### ISSUE TITLE
Security Update

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#195]
**Proposed Domain**
All over the place.

**Content Summary**
We need to more clearly provide people information about data security standards at the Hutch but unfortunately it needs to go pretty much all over the place.  

I am going to suggest we create: _compdemos/dataSecurityStandard.md
Then summarize what can be made public from this document: https://centernet.fredhutch.org/cn/u/hdc/_jcr_content/leftParsys/download_0/file.res/Fred-Hutch-Information-Classification-and-Handling-Standard-FINAL.pdf

At the top of the page we need to specifically link to the ISO page in CenterNet AND to this pdf.  

Then we need to distribute links to the demo page around the Wiki.  So in all three domains we're going to need to insert some references to security and link to this demo page.  

**Local Content Expert(s)**
I can start.  @sgglick  will review after I take a stab at this.

**Comment by vortexing** [comment]
OK!  We are proposing to make this page:
https://sciwiki.fredhutch.org/generation/human_privacySecurity/

THE PAGE about data privacy and security in the Wiki, both for human data security and other data that has security concerns related to it.  

@ptvan and I will go through and add links to this page from around the Site when data security is an issue.  Also we will take chunks of discussion we find about Security out of other pages and put them here when relevant.  OR link out to them when it makes more sense for that information to live elsewhere.  

@sgglick and @bdconnolly Can you focus your editing efforts regarding data security to this single page for the time being?  This page can become an overview of the more detailed content that you can link to inside CenterNet.

**Comment by vortexing** [comment]
I have separated the Data Use Agreements and such into a separate page here:
https://sciwiki.fredhutch.org/generation/security_legal/

This will allow for the above page to only be data types and associated security guidelines.

**Comment by sgglick** [comment]
Ok, will review.

**Comment by vortexing** [comment]
@sgglick  and @bdconnolly What do you think about this issue?  Can we close it and you both know all things security go to this page (and all things legal goes to security_legal).

**Comment by vortexing** [comment]
I think this is addressed as much as is going to be.  Please do weigh in on future security issues as things change.
