### ISSUE TITLE
Migrate Tensorflow 

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#198]
There are two articles on the SciComp wiki "Installing CUDA8 on Ubuntu" and "Using Tensorflow on Rhino" (the former references the latter) that likely could be moved over. 
(1) Do we want to move these over ? They're definitely useful and I don't see any Hutch-specific sensitive info...
(2) Where would they go ? Maybe under Bioinformatics with an intro landing page ("How to do machine learning with Hutch resources" ?), The CUDA8 stuff feels more like Scientific Computing though.... @vortexing any thoughts ?

**Comment by vortexing** [comment]
@dirkpetersen You wrote both of those pages so I think it'd be great to get your take/your stamp on the transition between sharepoint and github wikis.

**Comment by vortexing** [comment]
Closed!!!!
