### ISSUE TITLE
getshiny.fredhutch.org fails for certain on-campus computers

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#206]
The "Shiny Applications" demo page (https://sciwiki.fredhutch.org/compdemos/shiny/) provides excellent information. One step in deploying Shiny Apps at Hutch is to fill out the form at getshiny.fredhutch.org. This website is accessible to Hutch IP only. However, my office desktop in Arnold connected to a wall Ethernet port, which can access rhino, CenterNet, etc... cannot access this page.

Perhaps we should at the very least mention "If you have trouble accessing this request page, please email scicomp with relevant details" ?

**Comment by ptvan** [comment]
@dtenenba now has the IP of my computer where this failed.

**Comment by dtenenba** [comment]
Well, not really. According to `checkip.amazonaws.com` the IP is 140.107.0.7, but that is moat, the firewall.

**Comment by ptvan** [comment]
So do we just want to punt this with some generic warning text until we have a solution/explanation ?

**Comment by dtenenba** [comment]
Not sure. Might ask @robert-mcdermott  and @atombaby about this. The app is hosted in the SciComp environment in Rancher.

**Comment by vortexing** [comment]
@ptvan @dtenenba what ever happened to this discussion?  I feel like it's over.  Thoughts?

**Comment by dtenenba** [comment]
There is something weird about the network in Phu's part of Arnold. We might want to escalate this to Network Engineering. I don't think we should discuss details of it, just say that if you have issues, email scicomp and scicomp can route them appropriately.

**Comment by vortexing** [comment]
I'm closing this.
