### ISSUE TITLE
TOC Anchors are broken

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#22]
Here is something I found about this theme regarding broken anchors.  I don't know enough to know how to fix it though.
https://github.com/mmistakes/minimal-mistakes/issues/1302

**Comment by dtenenba** [comment]
@vortexing Do you want me to try and implement the solution described at https://github.com/mmistakes/minimal-mistakes/issues/1302#issuecomment-393223142 ?

**Comment by dtenenba** [comment]
OK, I don't have time at the moment, but it bugs me. Really they should fix it upstream. But if I decide to work on this I will let you know.

**Comment by vortexing** [comment]
Sounds like a plan.  This undertaking is a sizeable time suck as it is, so drawing the line somewhere is important.

**Comment by atombaby** [comment]
This was apparently fixed in [4.15.0](https://github.com/mmistakes/minimal-mistakes/releases/tag/4.15.0)

**Comment by atombaby** [comment]
verified working
