### ISSUE TITLE
Update and smooth out Computing Resource Access Methods page

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#220]
**Proposed Domain**
This page specifically
https://sciwiki.fredhutch.org/computing/access_methods/

**Content Summary**
Add some introductory material including the blurb about how X11 works as a client and get the content on the page organized in a logical flow.  

**Local Content Expert(s)**
@bmcgough and friends.

**Comment by rbarfield** [comment]
Long time reader, first time issuer (commenter? questioner?). Also for this page would it be possible to add something about remote desktop clientele for macs or a link to the necessary webpage? Also, would it be possible to add something about mapping to the fast cluster in the mac finder (similar to this page http://osxdaily.com/2010/09/20/map-a-network-drive-on-a-mac/)? Apologies if this is already located on the page and missed it.

**Comment by vortexing** [comment]
Also, there is a link to the old wiki about how to set up NoMachine here:
https://sciwiki.fredhutch.org/computing/linux_linux101/#linux-at-the-fred-hutch

Please remove!!!!

**Comment by vortexing** [comment]
Addressed by Restructuring.
