### ISSUE TITLE
Improving "Hypotheses in the Era of Large Scale Molecular Data" page 

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#231]
**Proposed Domain**
Generation

**Content Summary**
https://sciwiki.fredhutch.org/generation/study_hypothesis/ : adding or expanding on statistical power calculation, adequate controls, subgroup analysis, Simpson's Paradox, etc... I also thought maybe a "Further Reading" section would be nice so we don't overwhelm readers. I have read "Experimental Design for Biologists" book by David Glass, it's OK but might be too philosophical and not stats heavy for this article. 

**Local Content Expert(s)**
@rbarfield is already on this, but wide input will probably be helpful

**Comment by vortexing** [comment]
@rbarfield are you ready for a pull request on this guy or are you still in progress?
