### ISSUE TITLE
Update environment modules page

### ISSUE THREAD

**Issue by bmcgough** [FredHutch/wiki#239]
**URL of page(s) of concern**
Specify the URLs of the page(s) where there are technical problems.
https://sciwiki.fredhutch.org/computing/cluster_software/#
**Describe problem**
Preface content with "the two ways to use modules" -
* module name - resilient but not reproducible - version loaded will change
* module name+version - reproducible but less resilient - user has responsibility to update scripts when versions change (ex: OS upgrade)

**Comment by vortexing** [comment]
I think this is done.
