### ISSUE TITLE
economy api Missing Links

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#251]
**Proposed Domain**
https://github.com/FredHutch/wiki/blob/master/_compdemos/EconomyCommand-API.md

**Content Summary**
There is section of the page that is missing a few links. Should potentially be added? Currently reads

*please check our HPC and data migration tutorials in the scicomp wiki at http://scicomp.fhcrc.org and the swc page on github for additional details:

- How to migrate large data to Economy File
- How to use Economy File and Scratch with Sequencing Data
- [swift commander on github](https://github.com/FredHutch/swift-commander)​
- [Check out this video how to the swc command](https://asciinema.org/a/17172)​
- HPC: using Economy File and Scratch on Gizmo*

Are the three that missing links pages that need to be developed or are they just missing? 

**Local Content Expert(s)**
@vortexing @FredHutch/scicomp

**Comment by dirkpetersen** [comment]
Fixed a link:  https://github.com/FredHutch/wiki/pull/255

**Comment by atombaby** [comment]
These links look to be fixed
