### ISSUE TITLE
Explain like I'm five: module load v ml 

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#257]
**Proposed Domain**
Computing - this page/section: https://sciwiki.fredhutch.org/computing/cluster_software/#environment-modules

**Content Summary**
Why would one want to use `ml` instead of `module load`?   Particularly when you can work out your process on rhino using ml, and then when you copy/paste it in your shell script to run non-interactively it breaks and you later realize you need to write it all out in your shell script?  Is there any benefit besides fewer keystrokes here, b/c the text makes it sound like there is.  

It sounds like it doesn't really matter which one you use in the text.  However, it DOES matter if you use it in a non-interactive setting and `ml` does not work.  

**Local Content Expert(s)**
SciComp

**Comment by vortexing** [comment]
I think, after discussing this a bit, I think we need some work on how to approach environment management and shell scripts and such. 

https://sciwiki.fredhutch.org/computing/cluster_software/

This page needs more enlightenment for beginners, including an example head of a shell script with an eye toward reproducibility, and a line-by-line explanation of what each line is doing and why you would want that.

**Comment by vortexing** [comment]
Related to Issu #239

**Comment by bmcgough** [comment]
I believe this and #239 are done. #239 is related to a milestone. Close these when that milestone is done?

**Comment by vortexing** [comment]
Done!!!
