### ISSUE TITLE
Broken Links on Overview of Computing at Fred Hutch

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#260]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/computing/comp_index/
**Describe problem**
Broken Links at "Software, Resources and Updates" header (last section on page) and "In-Person Training and Office Hours"  (link listed in last section on page)

**Comment by rbarfield** [comment]
@FredHutch/scicomp @vortexing @ptvan

**Comment by vortexing** [comment]
closed
