### ISSUE TITLE
Mention Perl

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#261]
**Proposed Domain**
https://sciwiki.fredhutch.org/bioinformatics/prog_unixbash/#

**Content Summary**
What do people think about potentially mentioning a bit on Perl? Recently ran into someone in lab who still uses it. Maybe useful to add a bit on it after "Go." I'm up to add a blurb on it if folks think it would be useful. 

**Local Content Expert(s)**
@ptvan @vortexing

**Comment by vortexing** [comment]
Asked on Slack for Perl users.  Will report back.

**Comment by vortexing** [comment]
Addressed by #271
