### ISSUE TITLE
Add rhino usage limits

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#272]
**Proposed Domain**

 - Computing

**Content Summary**

 - Create page with rhino usage "policies"
 - Add link in https://sciwiki.fredhutch.org/computing/oldpages/cluster_rhinoGizmo/#rhino

 c.f. Issue #245 

**Local Content Expert(s)**

@dirkpetersen @atombaby @bdconnolly

**Comment by vortexing** [comment]
This information could go in this page:
https://sciwiki.fredhutch.org/scicomputing/compute_platforms/
It also needs some additional pruning/text about what exactly IS all that stuff in the tables.

**Comment by vortexing** [comment]
I think this is somewhat addressed as best as it can be, OR parts of this larger issue are addressed by smaller, more discrete issues that are still open.
