### ISSUE TITLE
Question on accessing storage

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#274]
**Proposed Domain**
[Using Mountain Duck or Cyberduck for Accessing Economy Storage](https://sciwiki.fredhutch.org/compdemos/Mountain-CyberDuck/#)'

**Content Summary**

Can Mountain and CyberDuck be used to access data from home/fast/or secure if working remotely? For example, if using a laptop and would like to move simulation results from the cluster-within home- to local machine (after VPNing) would I use these clients? Is there a page somewhere on the Hutch with this information? Could be useful to have a link from this page on storage to that page. Sorry if this has already been addressed and I just missed it.

**Local Content Expert(s)**

**Comment by vortexing** [comment]
Let's add this here:
https://sciwiki.fredhutch.org/computing/access_methods/

- how to map a network drive on your mac or pc
- how to use a client for that if you do not want to map it to the computer you're working or using remote desktop

When you're working on a local computer but using files stored remotely is the goal here.

**Comment by rbarfield** [comment]
For Mac OS appears to be the following:

1) VPN in. 
2) Open up Finder
3) Click on Tab Go->Connect to Server (or do cmd+K)
4) For homelink enter: smb://homelink/homes
     For Fast enter: smb://center.fhcrc.org/fh/fast

5) Enter your login

I do not know how to do for PC. Does anyone know a similar approach? Is it ok to add the following to the wiki or do we not want people accessing the cluster in this manner?

**Comment by rbarfield** [comment]
For PC it appears to be.

1) VPN in
2) Open up File Explorer
3) Go to Computer
4) Click on Map Network Drive
5) Enter \\homes\homelink or \\center.fhcrc.org\fh\fast

Again. Wondering if there is another preferred way @FredHutch/scicomp
