### ISSUE TITLE
resource_overview.md

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#295]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/computing/resource_overview/

**Describe problem**
There's this strange text string:
"<!– ## Self Service Resources Jupyterhub, RStudio, db4sci, Galaxy, etc."

Under the Proposed Preparation section. Also under that is a section titled Gory details of cluster. This Gory section does not seem to appear (at least for me) when view the page in markdown mode in GitHub. Assuming just a left over comment out?

**Comment by vortexing** [comment]
Fixed in new domain!
