### ISSUE TITLE
Computing Tutorials

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#30]
Took a minute in the sharepoint wiki to ponder the previous experience vs a re-imagining.  On the training side of Computing, I would, from my previous experience, love to see the following topics be covered, and have included links to some places in Sharepoint where there might be some content to keep or start from.  Some of these maybe the sentiment behind them was on point but perhaps it may not be helpful to actually copy and paste.

**Unix 101 and the Command Line:**
- @atombaby do you have the original slides here that we could make into an article?
- https://teams.fhcrc.org/sites/citwiki/SciComp/Training%20Materials/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fcitwiki%2FSciComp%2FTraining%20Materials%2FUnix%20101&FolderCTID=0x012000A48F33362DEBCC4D8F5F649F15E7E72E&View=%7B979DF0D6-9283-47DB-A662-3425961CAA74%7D
- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/SSH%20Disconnection%20Solutions.aspx

**Gizmo 101:**
- https://teams.fhcrc.org/sites/citwiki/SciComp/Training%20Materials/Forms/AllItems.aspx?RootFolder=%2Fsites%2Fcitwiki%2FSciComp%2FTraining%20Materials%2FIntroduction%20to%20Gizmo&FolderCTID=0x012000A48F33362DEBCC4D8F5F649F15E7E72E&View=%7B979DF0D6-9283-47DB-A662-3425961CAA74%7D
- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Running%20X11%20Apps%20on%20rhino%20and%20gizmo%20nodes.aspx 
- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Gizmo%20Cluster%20Quickstart.aspx

- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Gizmo%20FAQ.aspx

- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Gizmo%20and%20slurm,%20when%20use%20srun,%20sbatch%20or%20salloc.aspx
- https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Cluster%20best%20practices.aspx

- Array job info but then subsequent help from @atombaby  was SUPER helpful in the past and particularly might be good to describe alongside how to use scratch adn approach pipelining/job organization.  Looking through my email, we had a pretty chopped up/naive (on my part) convo so maybe I have nothing to really contribute here besides the script you wrote for me.  

**AWS 101:**
AWS Credentials
https://teams.fhcrc.org/sites/citwiki/SciComp/Pages/Getting%20AWS%20Credentials.aspx

**Comment by atombaby** [comment]
@vortexing it looks like the source for those tutorials has been lost to time.  Do we want to have tutorials in the wiki?  Maybe we should include the stuff fredhutch.io is doing instead?

**Comment by vortexing** [comment]
OK, closing this b/c the new issue to re-make the new version of this is in issue #86
