### ISSUE TITLE
infodemos/usingS3withRhino still search-indexed but returns 404 

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#300]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/infdemos/usingS3withRhino/

**Describe problem**
As of this morning if you search "AWS S3", the second hit is "Using Scratch Temporary Storage with AWS S3 buckets and rhino" which points to the URL above, but if you click on the search result it takes you to a broken page with a 404. I'm not sure how often search indexing is done, and whether search results can be manually pruned, but seems like one of the two options will be needed. Seems like this is related to #291

**Comment by vortexing** [comment]
Closed by Dan's re-tooling of our search.
