### ISSUE TITLE
How to safely, sanely, safely, safely store data in AWS S3 buckets publicly

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#301]
**Proposed Domain**
Computing, and/or Resource library.

**Content Summary**
How to add contents to Hutch S3 buckets and *safely*, *very, very safely* make it publicly accessible. @dtenenba provided very useful reponses to Jenny Smith in the Coop wiki. I referenced this in #300 

**Local Content Expert(s)**
@dtenenba since he gave the original answers, but anyone else who wants to add things...

**Comment by atombaby** [comment]
https://sciwiki.fredhutch.org/scicomputing/store_objectstore/#sharing-data-with-other-collaborators
