### ISSUE TITLE
Example repository docs addition for scicomp_flask_examples

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#306]
https://github.com/FredHutch/scicomp_flask_examples

This is a good repo of flask instructions!  Let's finish the docs and get it linked into the Wiki.

**Comment by vortexing** [comment]
Let's make a resource library entry to introduce this resource.

**Comment by dirkpetersen** [comment]
There is also https://github.com/FredHutch/wiki-code-examples, https://github.com/FredHutch/slurm-examples

**Comment by dirkpetersen** [comment]
there is also https://github.com/FredHutch/IT/tree/master/flask

**Comment by k8hertweck** [comment]
We do have a flask template: https://github.com/FredHutch/flask-python-template

It would be nice to differentiate between the example and the template, and merge if necessary (at least the documentation).

Ideally, we'd have two repos (the template and then an example using it), with the process used to create the example documented in the a wiki demo

**Comment by laderast** [comment]
Still relevant?
