### ISSUE TITLE
How to use NoMachine docs

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#314]
**Proposed Domain**
Scientific Computing

**Content Summary**
Tell us how we should use NoMachine on rhino's

**Local Content Expert(s)**
@dirkpetersen

**Comment by rbarfield** [comment]
Would it be possible to have ore info on this? Specifically also in relation to R/Rstudio (https://sciwiki.fredhutch.org/scicomputing/software_R/). I do not see Rstudio as one of the programs readily available within nomachine. Is this something that we can install within NoMachine?
