### ISSUE TITLE
Data Management Documentation Inspiration!!!

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#32]
@jordanlsmith found a bunch of other institution's sites about research data management and I wanted to share them here so everyone could have some inspiration for what we might like to make for Fred Hutch.

Cornell: https://data.research.cornell.edu/

Specifically awesome is Cornell's data storage finder:  https://finder.research.cornell.edu/storage

Stanford's Best Practices for researchers: https://library.stanford.edu/research/data-management-services/data-best-practices

Less awesome, but still in existence, Stanford's storage and backup page: https://library.stanford.edu/research/data-management-services/storage-and-backup

Data management plans (more for me/the Generation page content, but still):  https://library.stanford.edu/research/data-management-services/data-management-plans

Stanford's training announcements: https://library.stanford.edu/research/data-management-services/consulting-training-and-other-services

Note: the library actually helps with this at Stanford.  I have not specifically pinged Arnold Library.  

Good old Harvard has lots of info about recommendations for Data Management:  https://datamanagement.hms.harvard.edu/

Just think about what WE could do!!!

**Comment by atombaby** [comment]
to be added to gendemos
