### ISSUE TITLE
Consider opening up contributions, but limit reviewers?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#330]
We as a group should consider a possible adjustment that would lower the bar required to contribute to the Wiki but still keep Fred Hutch staff as the reviewers for content to be merged into master.

We could use the codeowners feature and use the AllFredHutch team as the codeowner for the whole site.  That would then let us allow anyone with a github username to contribute, possibly through a fork, or via a branch like normal, and then would require a review from someone IN the Fred Hutch to get the content merged in.  

That might be more friendly to our local collaborators but still keep the security and content review sort of under our umbrella.  

@dirkpetersen @FredHutch/scicomp:  thoughts?

**Comment by k8hertweck** [comment]
I'm personally very supportive of any action that lowers the bar for participation here in the wiki.

**Comment by vortexing** [comment]
Well, I'm not sure it's "working" .  We've confirmed that non-fred hutch people can contribute when clicking "edit this page" and it will force them to fork it and do the PR from there.  That's fine now but doesn't let people edit/add to their contributions b/c others don't have permissions to edit their fork.  It works for small contributions for sure.  

I don't know yet if non fredhutch people can make a branch and PR though.

**Comment by vortexing** [comment]
OK I have opened up editing ability to anyone but limited the review process to those of us that opt into the Wiki-Reviewer github team.

**Comment by k8hertweck** [comment]
Is there info somewhere about how to opt in as a reviewer?

**Comment by vortexing** [comment]
Good point... I will add something to the readme.  Thanks for the reminder!!
