### ISSUE TITLE
Links to slurm documentation

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#339]
Slurm docs are available on the schedmd website, but these will often not match the version installed on our clusters.

I've installed a web server and the HTML docs on the controller, but we'd be adding links to internal systems.  It might be possible to add these to the wiki.  Does anyone have any opinions on how we might address this?

**Comment by vortexing** [comment]
@atombaby is this still a thing?  Did things get resolved at some point since then?

**Comment by atombaby** [comment]
Ah- SchedMD has started keeping old docs around:

https://slurm.schedmd.com/archive/slurm-18.08.3/

**Comment by vortexing** [comment]
This is done!
