### ISSUE TITLE
Edit link on sciwiki CN page for SciComp

### ISSUE THREAD

**Issue by cjbonner** [FredHutch/wiki#351]
Hi @vortexing ,

On the [SciWiki CenterNet page](https://centernet.fredhutch.org/cn/u/bdsc/sciwiki.html), clicking on the _Computing_ header returns a 404.  It should probably point to this URL:  https://centernet.fredhutch.org/cn/u/hdc/scicomp.html

Thanks,  Cathleen

**Comment by vortexing** [comment]
Done!
