### ISSUE TITLE
Quick Start guide

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#353]
**Proposed Domain**
Scientific Computing, preferably linked on front page/overview. 

**Content Summary**
Quick Start guide for new employees, giving a plain-language overview of resources and where to find appropriate information/help.  

**Local Content Expert(s)**
Well, um...I guess me?

**Comment by k8hertweck** [comment]
Notes from convo between CompBio faculty and SciComp about what things are useful to know for new computational researchers:

what servers are available where
- Overview: https://sciwiki.fredhutch.org/scicomputing/compute_overview/

that you have to email someone to get a home directory and get cluster access
- There is no need to email anyone for a home directory. Home directories are automatically created.
- If CompBio staff use HomeLink, then, they will need to send an email to scicomp@fredhutch.org with the subject “Homelink account for <hutch-id>” 

snail is how you log in off campus
- https://sciwiki.fredhutch.org/scicomputing/access_methods/#access-via-a-remote-location
- Setting up passwordless login and ssh forwarding https://sciwiki.fredhutch.org/scicomputing/access_methods/#advancedoptional-setup-for-making-things-easier-the-ssh-config-file

description of how to set up passwordless login using SSH keys
- How to access computing resources: https://sciwiki.fredhutch.org/scicomputing/access_methods/
- Covers everything from which ssh clients to setting up ssh config file
- Setting up passwordless login and ssh forwarding https://sciwiki.fredhutch.org/scicomputing/access_methods/#advancedoptional-setup-for-making-things-easier-the-ssh-config-file

example .ssh/config setting up X forwarding
- https://sciwiki.fredhutch.org/scicomputing/access_methods/#advancedoptional-setup-for-making-things-easier-the-ssh-config-file

that we use slurm for scheduling, and links to docs
- https://sciwiki.fredhutch.org/scicomputing/compute_jobs/

Docker is only available on exmar, and you do have to email to get on that
- If access to docker on exmar is required please send an email to scicomp@fredhutch.org with the subject “Permission to use Docker on exmar for <hutch-id>”

tmux is very helpful 
- SciComp currently does not have documentation or examples for using tmux (added note from Kate: tmux is mentioned here: https://sciwiki.fredhutch.org/scicomputing/access_methods/)

**Comment by matsen** [comment]
I would love to have this as a standalone wiki page!

There is clearly a ton of rich information on the wiki pages, but having something stripped down that fits on a 1/2 page would be great. We can strike tmux from the list if we want, though I think that something like screen/tmux is essential for using servers. Otherwise what happens when you shut your laptop?

**Comment by matsen** [comment]
Oh, and also let's work on making this the awesome wiki findable from the centernet search. "cluster" and "server" should take me there.

Also, can we please put a big banner on the old wiki that points people to the new site?

**Comment by dirkpetersen** [comment]
Re Docker: exmar is not the default for using docker. Here is the page for docker users https://sciwiki.fredhutch.org/compdemos/Docker/

**Comment by dirkpetersen** [comment]
> Oh, and also let's work on making this the awesome wiki findable from the centernet search. "cluster" and "server" should take me there.

I asked Centernet to update the stop words 

> Also, can we please put a big banner on the old wiki that points people to the new site?

done

**Comment by matsen** [comment]
> Re Docker: exmar is not the default for using docker. Here is the page for docker users https://sciwiki.fredhutch.org/compdemos/Docker/

Thanks @dirkpetersen . Will exmar go away? I do like having it around, as I can have long-lived tmux sessions on it that I use for fiddling around with Docker containers.

More generally: is this "quickstart" page going to happen? I did have a good chat with another faculty member, who thought that it would be great to have. The current docs are great, but they're a lot for someone new.

**Comment by k8hertweck** [comment]
I'm planning to attend the wiki meeting this week and will draft a quick start page. I'm envisioning it as a bird's-eye view of resources and technical on boarding for new folks who have worked with remote access, etc at other institutions.

**Comment by k8hertweck** [comment]
@vortexing and I agree that this information should be included on the [Large Scale Computing Overview](https://sciwiki.fredhutch.org/scicomputing/compute_overview/)

**Comment by dirkpetersen** [comment]
@matsen, Exmar will need to go away when it is EOL. The machine it is running on  14.04 and was purchased in 2010. We will likely not be able to migrate it to 18.04.  Most people found this to work OK but it does not have access NFS  to fast file: "prox new --docker mynewbox" .... if there is a need for a docker machine with certain features we can bring that up.

**Comment by k8hertweck** [comment]
Quick start guide is a PR in #368. This doesn't include a mention of docker, but does link to cloud resources. I'm happy to add any other brief essentials folks find necessary.

**Comment by vortexing** [comment]
Seems legit to me for the basics.  I hooked it up to the sidebar so people can SEE it.  Maybe people can weigh in and add stuff?  Looking at the list above (and filtering out stuff that likely people should be avoiding using), the basics of the request are covered.  I will go leave a approving review but will not merge the pull request until @matsen or someone weighs in about whether it's complete enough to add for now.

**Comment by vortexing** [comment]
Ah, I now see Kate did the sidebar in the other PR.

**Comment by matsen** [comment]
Closed by https://github.com/FredHutch/wiki/pull/368, no?
