### ISSUE TITLE
Ideas for Data Storage 

### ISSUE THREAD

**Issue by rbarfield** [FredHutch/wiki#354]
**Proposed Domain**
https://sciwiki.fredhutch.org/scicomputing/store_overview/
https://sciwiki.fredhutch.org/scicomputing/store_posix/
https://sciwiki.fredhutch.org/scicomputing/store_objectstore/
https://sciwiki.fredhutch.org/scicomputing/store_scratch/

**Content Summary**
Would be nice to go through and add links connecting all the pages. For example, this phrase shows up a few times:

_Note: Currently it is recommended to use a combination of Economy, Scratch and Fast. Please see our other storage pages for more information about what storage locations are best for what type of data and uses._

Could simply add links there for economy, scratch, and fast. 

Happy to do. 

In addition:

Question: Scratch is listed in store_posix but has it's own page, should add links in text of store_posix to store_scratch.

Question: On store_overview there are these two really nice tables `Storage Allocation and Costs` and  `supported features`. What would people think of having those tables repeated at top of store_posix, store_object, store_scratch and highlighting the storage focusing on, on that page. 

For example: On store_objectstore would have

|  Feature 	|  **Economy File** | 
|:-	|:-:	|
|  Encryption at Rest 	|      **X**	|
|  Encryption in Transit	|   **X**	|  
|  Access auditing |   **X**	| 
|  Approved for PHI by ISO 	|  **Yes**	|  

And also

Storage Resource | Costs (per TB/month)\*  | Backup Location/Duration | Best Use
--- | --- | --- | --- 
`Economy Local` and `Cloud` | $ beyond 5TB per PI |  Multi-datacenter replication, 60 day undelete with request to `helpdesk` | Best for archiving large data sets, or primary storage of large files.  Good for PHI or other data that requires encryption and auditing. *Requires Desktop Client to access*

Just a thought, may make it easier for non-comp people to get through. 

Feedback?

**Local Content Expert(s)**
@vortexing @dirkpetersen @tsibley

**Comment by sgglick** [comment]
Instead of pointing to Berkeley's page for PHI, I will create a similar HDC page, and also add an HDC page for PHI and research.  Once done, I will put these links into these pages on the wiki, and anyplace else that is needed.

**Comment by atombaby** [comment]
@rbarfield sounds like a good idea to me.  Probably the best way to implement would be one of those YAML databases in `_data` so we can manage all the information in a single place and get consistent information to the readers.

**Comment by rbarfield** [comment]
Hi @atombaby , that sounds good. I will be honest that I am not familiar with YAML databases. I see you've self-assigned that. Will you be taking care of that part? I will go ahead and go through and add  the links.

**Comment by rbarfield** [comment]
Have gone through and added the links to the branch links_data_storage to the 
https://sciwiki.fredhutch.org/scicomputing/store_posix/
https://sciwiki.fredhutch.org/scicomputing/store_objectstore/
https://sciwiki.fredhutch.org/scicomputing/store_scratch/

I'll go ahead and create pull request unless want to commit the tables to that branch.

**Comment by atombaby** [comment]
@rbarfield I'm thinking lets merge that branch into _mrg/issue_354_.  I've created https://github.com/FredHutch/wiki/pull/363 for that.  I think you should be able to OK the merge if you think this is a good way to do it.

**Comment by rbarfield** [comment]
Sounds good. Went ahead and approved.
