### ISSUE TITLE
Broken links at https://sciwiki.fredhutch.org/scicomputing/compute_platforms/

### ISSUE THREAD

**Issue by ptvan** [FredHutch/wiki#356]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/scicomputing/compute_platforms/

**Describe problem**
In the paragraph for Rhino there is this text: "More information on the topic of ssh configurations for access to rhino can be found [here]. " There [here] link points to https://sciwiki.fredhutch.org/compdemos/ssh/, which no longer exists.

**Comment by k8hertweck** [comment]
Oof. I'm finding more broken links resulting from domain shuffling. 

[This link](https://sciwiki.fredhutch.org/scicomputing/resource_overview/) is broken in the section on Cloud Computing on [this page](https://sciwiki.fredhutch.org/scicomputing/compute_overview/).

I imagine there are others, but we need a thorough double check.

**Comment by k8hertweck** [comment]
Reopening as per my last comment here; I'll try to do a check on the computing domain sometime this week.

**Comment by vortexing** [comment]
Closing this because the original issue was addressed, we know we need to do a large overhaul of checks but it requires a technical solution, and also work on the overview pages is underway/in another issue.
