### ISSUE TITLE
Link cross referencing in CenterNet

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#357]
**URL of page(s) of concern**
ALL OF CENTERNET

**Describe problem**
Let's make sure we've coordinated all appropriate links to this wiki (and among other resources) among the set of CenterNet pages relevant to us.

**Comment by vortexing** [comment]
The scope fo this issue is overwhelming. :)

**Comment by vortexing** [comment]
This issue still makes me laugh.  
```
URL of page(s) of concern
ALL OF CENTERNET
```

**Comment by k8hertweck** [comment]
Never forget.

**Comment by vortexing** [comment]
Where is the "never close this" label for issues?

**Comment by k8hertweck** [comment]
Probably right next to the "impossible dream" label

**Comment by vortexing** [comment]
hahahhahahah.   April 30th, 2020 and this is STILL REAL.

**Comment by vortexing** [comment]
2024 and we're giving up.
