### ISSUE TITLE
Troubleshooting error messages from batch jobs on cluster

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#367]
**Proposed Domain**
Scientific Computing, associated with cluster resources

**Content Summary**
What are common error messages folks receive when running batch jobs, and what are ideas to resolve them?

Examples:
- Resources priority
- Min memory
- Resource limit

**Local Content Expert(s)**
Hey SciComp folks! I bet you hear these types of questions all the time!

**Comment by atombaby** [comment]
More updates in fc181261bebdfdb4e0e1c320793d691784ddbc27

**Comment by k8hertweck** [comment]
Example error: "QOS min cpu not satisfied"

**Comment by vortexing** [comment]
Duplicate of issue #278

**Comment by k8hertweck** [comment]
Ahhhh that was not recognizable from the title of the other issue. Would you like for me to move these comments there?

**Comment by vortexing** [comment]
This is done!
