### ISSUE TITLE
mention motuz

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#372]
**Proposed Domain**
Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.

Scientific Computing

**Content Summary**
Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded.  

Mention the existence of motuz, what it does, and how to use it.

**Local Content Expert(s)**
Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too). 

@dtenenba

**Comment by vortexing** [comment]
This should be closed.
