### ISSUE TITLE
add detail and external links for tmux

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#374]
**Proposed Domain**
Scientific Computing, [Access methods](https://sciwiki.fredhutch.org/scicomputing/access_methods/)

**Content Summary**
Include links to external documentation and examples for usage

**Local Content Expert(s)**
@k8hertweck

**Comment by vortexing** [comment]
Was this sufficiently done for your liking here: https://sciwiki.fredhutch.org/scicomputing/access_methods/#screen-and-tmux
?
