### ISSUE TITLE
R validation (for use in clinical trials, etc)

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#387]
**Proposed Domain**
[R and RStudio page](https://sciwiki.fredhutch.org/scicomputing/software_R/), new subsection.

**Content Summary**
Information about use of R in clinical trials and how base R and other packages are validated 

**Local Content Expert(s)**
me

**Comment by k8hertweck** [comment]
- installation validation (environment maintenance and consistency), associated documentation provided on startup
- risk-based approaches (suggested by R Validation Hub) say package is validated by community if passes certain level of threshold of downloads/users

**Comment by k8hertweck** [comment]
Software is built at the Hutch using EasyBuild, which provides citable environmental consistency.

**Comment by vortexing** [comment]
@monicagerber This feels like now your domain to fill or kill.  I ordain you!!!!!
