### ISSUE TITLE
Update Shiny app documentation

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#388]
**Proposed Domain**
Here is the intro to what Shiny is, maybe we could add why you would want to use it, info about the monthly shiny meeting, etc: https://sciwiki.fredhutch.org/scicomputing/software_R/#shiny @k8hertweck 

Here are the Fred Hutch shiny app deployment instructions that need polishing/updating:
https://sciwiki.fredhutch.org/compdemos/shiny/
@dtenenba 

**Content Summary**
Perhaps we should clean things up related to shiny as it stands right now in case anyone wanted to have a public Shiny Party.

**Comment by k8hertweck** [comment]
Yes, and it should also get added to the training and community groups page: https://sciwiki.fredhutch.org/scicomputing/reference_training/

**Comment by vortexing** [comment]
@dtenenba how do you want people to do shiny apps now?  Is this content still relevant or could we simply tell people to add their app to a new repo just for it and then fill out the getShiny form?

**Comment by dtenenba** [comment]
https://sciwiki.fredhutch.org/compdemos/shiny/ is still accurate.

**Comment by vortexing** [comment]
The master has spoken.
