### ISSUE TITLE
GitHub org

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#394]
**Proposed Domain**
Scientific Computing, Sharing Code and Data

**Content Summary**
Clarify description of what can be done with the FH GitHub org from this page: https://sciwiki.fredhutch.org/scicomputing/software_managecode/

- [ ] disambiguate language among sections
- [ ] email `helpdesk` (page above) or `scicomp` (from here: https://sciwiki.fredhutch.org/scicomputing/access_credentials/)
- [ ] working with groups (creating teams, etc)
- [ ] add GitHub to title of "managing code" section to improve search results
- [ ] add link to new GitHub org identity tracking system being created by scicomp

This issue came about through questions from someone on Slack

**Comment by k8hertweck** [comment]
We should also specify if we have any expectations (or even recommendations) about how projects are managed (e.g., permissions to repos, naming of repos, etc)

**Comment by k8hertweck** [comment]
Final verdict: email scicomp to get added to GitHub org

**Comment by k8hertweck** [comment]
About managing groups: we may eventually move towards a system of automatically creating groups based on departments, etc. For now, members of the org are allowed to create their own teams. Nested teams are available. Recommendations:
- writers
- viewers/reader
- managers/admin

**Comment by vortexing** [comment]
Can we close this for now?  There is the other issue re: github onboarding docs when they are ready.  Can we leave that one open as it is more discrete and specific?
