### ISSUE TITLE
Try to improve Overview sections by making them less dense

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#397]
Review these pages:

- ~~https://sciwiki.fredhutch.org/scicomputing/access_overview/~~ - [DONE](Chilliwack patch 1 #462) 
- https://sciwiki.fredhutch.org/scicomputing/store_overview/
- https://sciwiki.fredhutch.org/scicomputing/software_overview/
- https://sciwiki.fredhutch.org/scicomputing/compute_overview/
- https://sciwiki.fredhutch.org/scicomputing/reference_overview/

And look for ways to reorganize or edit those pages to make them less dense

**Comment by vortexing** [comment]
Going to close this because it's sort of part of other issues and pretty broad.
