### ISSUE TITLE
Attempt to clean, streamline and better curate the wiki README

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#399]
Attempt to clean, streamline and better curate the wiki README:
https://github.com/FredHutch/wiki/blob/master/README.md

**Comment by vortexing** [comment]
Took a stab at this.  Did it address your concerns?

**Comment by Chilliwack** [comment]
Indeed! looks better! also made some updates to it that are in https://github.com/FredHutch/wiki/pull/476
