### ISSUE TITLE
Outline a tiered path of least resistance for contributing to this wiki

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#400]
Outline a tiered path of least resistance for contributing to this wiki that can handle users such as:

1. New to Git? Here is the easiest most straight forward way to contribute so much so your grandma can do it
2. You know git and you got alot of content to post try this method of working with git
3. You are a git god or on your way so here is some additional ways we recommend to get the most out of git and maximize your workflow..

Then find some lemmings to offer these paths to and refine further based on observations and their input

**Comment by Chilliwack** [comment]
10/3 Convo w/ Dirk - gave update on a new git user onboarding flow to git FH org

**Comment by vortexing** [comment]
I did a tune up of the readme.md a while back.  Perhaps that has in part gotten this issue addressed?

**Comment by Chilliwack** [comment]
Good morning @vortexing !! Hey I was thinking can I park the content to address this issue #400,  [here](https://sciwiki.fredhutch.org/contentproviders/) as well as flush out and include what is already outlined on [said page](https://sciwiki.fredhutch.org/contentproviders/)? Would you be kewl with that idea??...just wanted to run it by you before I dedicate time.
