### ISSUE TITLE
Install google analytics on wiki page so we have an idea of traffic

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#405]
Install google analytics on wiki page so we have an idea of traffic

https://www.reddit.com/r/github/comments/9kbu5d/github_pages_how_to_check_traffic/

**Comment by vortexing** [comment]
talk to @bmcgough about this

**Comment by Chilliwack** [comment]
We got analytics!!! Thanks @bmcgough for granting me access. I'm throwing together a dashboard now which can be seen here [SciWiki Analytics dashboard](datastudio.google.com/reporting/40a1e46d-9845-46d1-ba41-1dcf77e69772) . It's a work in progress...Im developing it as I have time and as I can get the data in. The only major thing missing is search data which we are currently not collecting but I'll create an issue focusing on setting it up so we can start collect the search data and then Ill load it into this dashboard. More to come!

**Comment by rcascioFHCRC** [comment]
The dashboard is really cool!

**Comment by Chilliwack** [comment]
Closed access to dashboard for the time being until I flush the rest out.
Need to add:
-Freq and Recen
-Count of
-Day since
-Engagement (both tabs)

**Comment by Chilliwack** [comment]
Closing this bc we do have google analytics installed on the wiki. AP, BM and JB all have access. We are collecting traffic and pageviews but we are not tracking search queries which would be of value so I've created a ticket here https://github.com/FredHutch/wiki/issues/412#issue-508591014 . Once I get done with some of these or issues Ill circle back and polish up the dashboard.

**Comment by vortexing** [comment]
Not sure which AP this is.  Is this me?  If so, can you refresh my memory offline as to how I have access? eek!
