### ISSUE TITLE
Update notifications, automated emails, prompts etc...so have updated links to wiki

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#406]
Update notifications, automated emails, prompts etc...so have updated links to wiki

When ppl use resources here there are notifications, prompts and emails they receive that has info and links. These need to be updated and redirected tot he updated and correct links on sciwiki

**Comment by Chilliwack** [comment]
Example from Dirk:

-----Original Message-----
From: hpcpol-bounces@lists.fhcrc.org <hpcpol-bounces@lists.fhcrc.org> On Behalf Of loadwatcher.py-no-reply@fhcrc.org
Sent: Friday, September 27, 2019 2:45 PM
To: Wu, Hanrui <hwu@fredhutch.org>
Subject: [hpcpol] RHINO2: You are using too many CPU cores!

This is a notification message from loadwatcher.py, running on host RHINO2. Please review the following message:

hwu, your CPU utilization on rhino2 is currently 549 %!

For short term jobs you can use no more than 400 % or 4.0 CPU cores on the Rhino machines.
Please reduce your load now and submit batch jobs or use the 'grabnode' command for interactive jobs.

see http://scicomp.fhcrc.org/Gizmo%20Cluster%20Quickstart.aspx
or http://scicomp.fhcrc.org/Grab%20Commands.aspx
or http://scicomp.fhcrc.org/SciComp%20Office%20Hours.aspx



If output is being captured, you may find additional information in your logs.

**Comment by vortexing** [comment]
No posting people's email addresses on github please. ;)

**Comment by Chilliwack** [comment]
touche...thank you!!

**Comment by vortexing** [comment]
This seems done to me.  I haven't seen evidence of the old wiki links for a bit.
