### ISSUE TITLE
Under Scientific Computing, identifying if your data is PHI or sufficiently de-identified has broken links. I will submit corrections next week.

### ISSUE THREAD

**Issue by sgglick** [FredHutch/wiki#408]
**Proposed Domain**
Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.

**Content Summary**
Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded.  

**Local Content Expert(s)**
Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too).

**Comment by vortexing** [comment]
I see your patch branches but no pull requests.  Do you want to do a pull request from each of your branches so that someone can review them and then get the edits merged in?

**Comment by vortexing** [comment]
@sgglick Did you intend to merge in the edits you put in the three patch branches you made?
