### ISSUE TITLE
info on storage options at fred hutch

### ISSUE THREAD

**Issue by strasser** [FredHutch/wiki#411]
**Proposed Domain**
Somewhere handy!

**Content Summary**
Let's create a spreadsheet/flow chart/info chart about storage options at the hutch! We should coordinate with CIT and SciComp who have worked on this in the past. Here's an outdated chart on Centernet: https://centernet.fredhutch.org/cn/u/center-it/services/storedataprotect.html. There's also a spreadsheet created by someone at CIT (Dirk might know who?) that we copied into google: https://docs.google.com/spreadsheets/d/1mpM8gIZHfuchFQkCgDn8-keaYKCq5I7N-ysUNUGGIVU/edit#gid=0

**Local Content Expert(s)**
Dirk might be able to answer questions about links above. plus the mystery CIT person.

**Comment by vortexing** [comment]
This is done as decided about a year ago b/c some of that content in the dead pages does not need  to be retained (we'd like to leave the past in the past).  I'm going to make an executive decision here that this is addressed.  Perhaps a nicer table in the existing page could be made to make this more accessible, but for now we have other fires.
