### ISSUE TITLE
Streamline Resource Library

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#413]
**Proposed Domain**
Update the Resource Library so that demos are more discoverable (e.g., move links to template repos, etc elsewhere, or minimize that section).
https://sciwiki.fredhutch.org/compdemos/

**Comment by k8hertweck** [comment]
The Data Generation section has the Resource Library linked in the overview. We should do this for the scientific computing section, too

**Comment by vortexing** [comment]
These are both done I believe.
