### ISSUE TITLE
Use the https://sciwiki.fredhutch.org/compdemos/ as parking spot for topical content shared during office hours

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#414]
@bmcgough had a good idea of developing set topics to discuss during SciComp office hours and create a schedule to rotate though those topics and make that schedule public..for example:

Week 1 - Bash/terminal
Week 2 - On Boarding..
Week 3 - Data Science
Week 4 - Run your first cluster job
Week 5 - Parallelization
Week 6 - How to use motuz
Week 7 - topic/free spot/free coffee?
Week 8 -  topic/free spot/free coffee?

This issue is for when this is all finalized and the content created for each topic lets host that content at the bottom of https://sciwiki.fredhutch.org/compdemos/

**Comment by vortexing** [comment]
Full support!

**Comment by Chilliwack** [comment]
This doesnt seem to be getting much traction....love the topics, and intent so I'm going to throw the topics @bmcgough mentioned into the content calendar for the Coop blog as I would like to create some blog posts about these so we can link and direct people to..

Week 1 - Bash/terminal - https://github.com/FredHutch/coop/issues/98
Week 2 - On Boarding.. - https://github.com/FredHutch/coop/issues/100
Week 3 - ~~Data Science~~ crossing off bc it's very broad and we have enough DS content to ref for ppl 
Week 4 - Run your first cluster job - https://github.com/FredHutch/coop/issues/101
Week 5 - Parallelization - https://github.com/FredHutch/coop/issues/102
Week 6 - How to use motuz - https://github.com/FredHutch/coop/issues/103
Week 7 - ~~topic/free spot/free coffee?~~
Week 8 - ~~topic/free spot/free coffee?~~

...and I'll close out this issue for the wiki
