### ISSUE TITLE
rename github repos wiki to sciwiki 

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/wiki#42]
Can we either name the website to wiki.fredhutch.org OR rename the github repos to sciwiki to ensure consistency

**Comment by bmcgough** [comment]
I think renaming the repo is fine. I will plan on doing that next week after everyone has had a chance to take a look at this issue and update outside links to the repo.

**Comment by vortexing** [comment]
That's fine but I'm not sure what it matters FOR, and we'll have to have all of our other authors and contributors be set up in the new repo correctly and communicate that they will need to reclone the new repo.

**Comment by vortexing** [comment]
We did it!!
