### ISSUE TITLE
Home directories on Rhino not automatically created for folks in admin

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#420]
Anyone with a HutchNetID can log on to Rhino, but may not have a home directory in Rhino if they are in admin (home directories are not automatically created for them). Such individuals can message scicomp to have a home directory created. 

This may be useful to add to [computing resource credentials](https://sciwiki.fredhutch.org/scicomputing/access_credentials/) or maybe [supported technologies](https://sciwiki.fredhutch.org/scicomputing/compute_platforms/)?

**Comment by dirkpetersen** [comment]
I would recommend not to document to this level of detail as this issue occurs only once or twice a year and if it changes we would have to update the docs. The general message should be that you should always message SciComp or create an issue here or ask slack if something does not work as expected.

**Comment by vortexing** [comment]
This is part of a larger fix that is something that SciComp is working on and anticipates in early next year it'll actually just not be an issue at all.  I think too this isn't Wiki-Work.  Closing this.
