### ISSUE TITLE
Connect with the GitHub/HutchNetID authentication tool being developed by SciComp

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#423]
This is a placeholder to remind us to update the GitHub organization documentation when SciComp is ready to release the GItHub/HutchNetID linking tool. I can work with @jefftucker to make this happen.

**Comment by vortexing** [comment]
@jefftucker or whoever, is this ready?

**Comment by vortexing** [comment]
@k8hertweck doesn't this work now?

**Comment by k8hertweck** [comment]
I don't think this has formally been implemented, but we can reassess if/when that happens
