### ISSUE TITLE
Orphaned pages/content?

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#424]
**URL of page(s) of concern**
https://sciwiki.fredhutch.org/scicomputing/software_linux101/

**Describe problem**
I can't see where this page is linked anymore; it's great content and I think should be included somewhere (maybe split between the Unix page and Comp Demos?)

We should also go through and see if there are other orphaned pages that aren't linked to anything else.

**Comment by vortexing** [comment]
Actually it IS liked but the flow/structure of the entire Software Development section needs to be re-done.  It's evolved away from the organization of the rest of the site as y'all have tuned it up and reenvisioned it. 

https://sciwiki.fredhutch.org/scicomputing/software_overview/

I will take a stab at remedying this b/c I have the long view here and then will ping you for a review once it's redone.

**Comment by k8hertweck** [comment]
Since #393 is related (reorganizing software dev overview), I went ahead and marked it "ready for review" in case you wanted to be able to hack on that.

**Comment by vortexing** [comment]
Addressed long ago.
