### ISSUE TITLE
Mention Slack communities that aren't currently listed 

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#428]
**Proposed Domain**
Scientific Computing, Training/Community: https://sciwiki.fredhutch.org/scicomputing/reference_training/

**Content Summary**
List the other Slack channels for communities, for which we don't have regularly occurring meetings (redcap, labkey, java, etc)

**Local Content Expert(s)**
Someone who is on Slack?

**Comment by vortexing** [comment]
This seems done.  Reopen if not.
