### ISSUE TITLE
Add recommendations for lab/PI file organization

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#429]
**Proposed Domain**
Scientific Computing, Data Storage

**Content Summary**
Provide guidelines for how to set up directory structures that are scalable across a lab, and can manage permissions for collaborators.

**Local Content Expert(s)**
Sci Comp?

**Comment by vortexing** [comment]
This is unlikely to be reasonable for SciComp b/c the ways in which people interact with their data are so very varied.  

However, the location of this could be built by researchers who are willing to describe how they organize stuff over here: https://sciwiki.fredhutch.org/gendemos/DataManagementGuidance/

**Comment by k8hertweck** [comment]
It's reasonable from a permissions perspective, since SciComp has to manage that for researchers. This also came from the recommendation of a lab member who had a convo with someone in SciComp about the same topic. It doesn't have to be policy, just an explanation of an example that makes sense. 

Also, I'm itching to update that page on Data Management

**Comment by bmcgough** [comment]
For this documentation location, I think general advice is appropriate, and I'm not sure SciComp is the best team to write it... or maybe we should just link to already published guidelines and general best practices?

We do have some commonality across labs like folders that we create and that have specific purpose and our group hierarchy and policies. But these are not really appropriate for publication. That being said, I don't think these things are documented internally and they really should be!

The Wikipedia article on [file system permissions](https://en.wikipedia.org/wiki/File_system_permissions) is a reasonable place to start. The last link looks pretty good. I wish I had time to write up a better explanation of POSIX users, groups, file systems, and permissions.

**Comment by vortexing** [comment]
@dirkpetersen is going to make the overview of the strategy for data management in Fast into a nice table over in:
https://sciwiki.fredhutch.org/scicomputing/store_posix/#fast

Beyond that I think this story is much much more complicated than a wiki can cover.

**Comment by k8hertweck** [comment]
At the very least, we need to explain that organization of data into projects, and also based on who will eventually need access to it, is a reasonable thing to mention. I know this is a difficult thing to summarize, but remain mildly optimistic we can provide a little more guidance through chaos.

**Comment by vortexing** [comment]
If there is a researcher in the community that feels that they have set their stuff up in a good way and are willing to write about it, it'd be great to have them contribute.  Otherwise this isn't a SciComp thing.  So we gotta find a writer!!  Maybe a Wiki-Editor?!?!!?

**Comment by laderast** [comment]
Should be DaSL product, not SciWiki
