### ISSUE TITLE
Plan for computing overview changes

### ISSUE THREAD

**Issue by bmcgough** [FredHutch/wiki#43]
I propose changing the layout of the compute index page (overview) to be more skeletal with links out to topics on other pages. I would also mirror this structure in the left sidebar. An overview paragraph would still exist at the top, but would be from a higher level than the current text. The rough outline would be something like:

- Access (laptops, desktops, VPN/wireless links, ssh, web services, getting help)
- Resources (hardware, cloud, services, etc.)
- Storage
- Cluster (gizmo, slurm, beagle, AWS Batch)
- Software (environment modules, languages, language resources)
- Linux (ssh, shell, scripting, X11)

Much of the content here may already exist so would just be links. Other pieces don't and will have to be created.

My goal here is to crate more of a timeline of information new researchers will need and present it in such a way as one can easily find the specific topic you want.

Comments and suggestions?

**Comment by vortexing** [comment]
In the other domains, the index page was solely intended to mimic the sidebar topics and provide a basic paragraph about each topic so the reader would know if they want to go to that page or not.  It would be best if you can keep your index page with a similar format.   Then each overview page in each topic ideally will be the basics of that topic, plus some basic information about the SUBtopics in the sidebar.  

I think your suggestions sound great and in line with the formatting in the other two sections (or it will be once the index page for bioinformatics and is for the generation domain), and get at the issue I was having with helping figure out what sidebar items need to be there for you all.  

I'm going to go through the Generation section and make the headings be links to the overview page for each individual topic.  It would be great if that would happen for you all too.

**Comment by vortexing** [comment]
@bmcgough I updated the site fairly massively to reflect your overview you have above and give you guys some clean slates.  Close the issue after you look at things if you think it's ok.

**Comment by vortexing** [comment]
done!!
