### ISSUE TITLE
Why is the search box now below the page footer on the search page?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#433]
This should not be.  It wasn't at the bottom before and now "suddenly" it is below the footer!?!?!
<img width="682" alt="Screen Shot 2019-10-31 at 2 11 05 PM" src="https://user-images.githubusercontent.com/13182518/67986485-5e06d000-fbe8-11e9-877a-0d049685704a.png">

**Comment by bmcgough** [comment]
I am guessing this is related somehow to the js function triggered by the search icon click - it adds a div for the search box, which is now appearing below the footer. Could the search box be created in the layout initially and hidden, just exposed by the search icon, @dtenenba?

**Comment by dtenenba** [comment]
This is what it looks like for me. Not below the footer. What browser are you using, @vortexing ?

![image](https://user-images.githubusercontent.com/2286826/68418353-edfacb80-014c-11ea-8e44-11e0c9014ddc.png)

**Comment by dtenenba** [comment]
oh wait, it's totally below the footer!
hang on...

**Comment by dtenenba** [comment]
Dunno but I will fix it.

**Comment by dtenenba** [comment]
Any objections if clcking the search icon took you to a separate page?
Just spitballing....not committed to this.

**Comment by bmcgough** [comment]
No objections from me - but a thought. @Chilliwack mentioned that Google Analytics can give us search term data if the terms show up in the url. That is currently not the case, but if it could be done with cloudsearch that might be cool? Or cloudsearch stats are also available?

**Comment by dtenenba** [comment]
Currently using Elasticsearch (not cloudsearch). 

Yeah, we could set it up so that the search terms are in the URL. 

This would probably be another reason to make search its own page.
