### ISSUE TITLE
making a Swift cloud connection in motuz

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#437]
**Proposed Domain**
Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.

**Content Summary**
Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded.  

making a Swift cloud connection in motuz

**Local Content Expert(s)**
Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too). 

@dirkpetersen   - since he did such a good job documenting this in slack ;-)

NOTE: We should probably not do this until the bug is fixed where hutchnet passwords are echoed back in plain text. Presumably it's also stored in a database. Also we should document that when your hutchnet password changes you need to update the cloud connection.

**Comment by vortexing** [comment]
Has this changed since this was posted @dirkpetersen or @dtenenba ??

This is all I see about it:
https://sciwiki.fredhutch.org/compdemos/motuz/#swift

**Comment by atombaby** [comment]
Swift is on its way to retirement- closing this issue as moot.
