### ISSUE TITLE
Rpmi/RSlurm content incorporation?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#438]
**Proposed Domain**
Scientific Computing

**Content Summary**
https://github.com/FredHutch/slurm-examples/tree/master/Rmpi-to-rslurm
This is beautiful.  Can/should we incorporate it into the Wiki proper?

**Local Content Expert(s)**
@dtenenba

**Comment by dtenenba** [comment]
@dirkpetersen what do you think?

**Comment by vortexing** [comment]
Seems like perhaps other RSlurm work might address this.
