### ISSUE TITLE
Refresh RSLURM!

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#441]
# URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/compdemos/rslurm_example/

# @ GitHub username of the listed primary reviewer of the page if known
@jennylsmith @fizwit 

# Specific information requests or concerns, or specific region on page of content to refresh.
Jenny was considering an even more basic example and John had a more complex example.  Perhaps you two can work together a bit on this?

**Comment by atombaby** [comment]
I am going to:

 - create a new page with an overview and basic example (e.g. calculating $\pi)
 - create a new page with a more complicated example translating loops to rslurm
 - create a new page translating an `apply` operation to rslurm

Then we'll incorporate the four pages (these three and the existing tximport) in some sensible manner.
