### ISSUE TITLE
display date that page was last modified?

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#444]
Is it possible to show (at the top of each page in the wiki) the timestamp when the page was last updated (i.e. date of last commit)? Right now there is a mix of older and newer documentation in the wiki and it would be nice if this was able to provide a clue as to how old the content is.

**Comment by vortexing** [comment]
Please, please, let's make this so!!

**Comment by vortexing** [comment]
Wait... I already did that!!!  IT's at the bottom of the pages Dan!!!  
<img width="650" alt="Screen Shot 2019-11-07 at 8 12 16 PM" src="https://user-images.githubusercontent.com/13182518/68449170-f679f300-019a-11ea-96a8-c01ef1c7797d.png">

**Comment by vortexing** [comment]
Let me see if I can move it to the top too!!!

**Comment by vortexing** [comment]
Only took 3 tries to realize I didn't have my endif at the end of the line like I thought I did....

It's really big font, but I guess that's ok?  If it is, Dan, close the issue.  Otherwise I can maybe try to make it smaller?
<img width="808" alt="Screen Shot 2019-11-07 at 8 35 42 PM" src="https://user-images.githubusercontent.com/13182518/68450020-4312fd80-019e-11ea-8c7d-df4452c7edec.png">

**Comment by dtenenba** [comment]
This looks good but the date is based on the `last_modified_at` field in the yaml metadata of the markdown page, but I want it to be based on the last commit date of the page. Otherwise we are counting on people to always update that field when they update a page, which does not happen often. We know the name of the original page (because we have the "edit this page" link) so we ought to be able to find the date of the last commit. Not sure exactly how atm....

**Comment by dtenenba** [comment]
OK, I think I managed to do this. Random plugins are not allowed in github pages so I made a web hook to a lambda function that writes out the file paths and last modified dates to a yaml file in the repo and commits it; then there is logic in the layout html template to display the last modified date.

If it works OK I will close this.

**Comment by vortexing** [comment]
WHOAAAAAAA!!!! Dan for the win!!!

This seems to work just fine.  I will work on removing all the manual `last_modified_date`s from all the pages b/c it isn't required anymore!! Maybe I'll try to do that as PRs get reviewed.  Also, I will endeavor to make the formatting slightly different so it's smaller at the top of the page.  Thanks Dan!!!

**Comment by dtenenba** [comment]
OK. I also noticed there were a couple pages that did not display the date. I didn't look deeply into it but it seems that those were pages that explicitly (as opposed to implicitly) declared the "single" layout (there is only one layout).

**Comment by vortexing** [comment]
Yes, that is an issue.  Maybe not bad though - any of the pages with content that a date might be important for would have the "Edit this Page" strip on it which comes from the _includes/social-share.html file.  I put your code there.  See if that makes the date show up on the relevant pages regardless of the layout.  We only overwrite the remote theme for one layout (the single layout).  The other layouts come from the remote theme as is.
