### ISSUE TITLE
Update Wiki Writer-Editor program point of contact

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#458]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/outreach/

### Specific information requests or concerns, or specific region on page of content to refresh.

Change Amy's name to Justin as point of contact. Also may need to update other details on this page.

### @ GitHub username of the listed primary reviewer of the page if known

@Chilliwack

**Comment by vortexing** [comment]
We can add Justin to the `sciwiki` email listserv and use that email as the contact email for the program.  Would be best to make sure multiple people are in on the communications so it doesn't hinge on one person.

**Comment by Chilliwack** [comment]
Requested access to sciwiki via help desk..more to come

**Comment by Chilliwack** [comment]
resolved in PR #462
