### ISSUE TITLE
Git Kraken instead of GitHub Desktop

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#48]
As per Kate's suggestion, I'd like to, and will start the process to, change/improve the GitHub tutorial to specifically reference using Git Kracken instead of GitHub Desktop for those of us who aren't using command line git.  

Links to include:
Git Kracken tutorial:  https://www.youtube.com/watch?v=ZKkMwTeAij4

Intro to github video: https://www.youtube.com/watch?v=0fKg7e37bQE

**Comment by k8hertweck** [comment]
I've been thinking about this as a part of my pilot testing of the Git/GitHub lessons I'm teaching next month. I'm electing this time around to teach with GitHub Desktop, but will also be doing demos of GitKraken and git integration with RStudio. My thinking is that as long as you understand how git works, the specific mechanism doesn't matter much, but GitHub Desktop seems a little less intimidating for folks who aren't familiar with it, and lacks the popups about subscribing to software like GitKraken. I'll let you know how it's received in my class!

**Comment by vortexing** [comment]
Gotcha.  After using Git Kraken since you told me about it, I do find that it is more challenging for a person like me who is new to github, git and version control in this manner at all.  

Would you be so kind as to review/edit/add your docs about using git and RStudio into the Github page in Bioinformatics:
http://sciwiki.fredhutch.org/bioinformatics/compute_github/

??

**Comment by k8hertweck** [comment]
Yes, I'll also add some notes on when GitKraken is more useful (e.g., when collaborating with forked repos)

**Comment by sgglick** [comment]
Here is something I thought about.  I work with Mike Nescot is ISO. As the institution moves  to Azure/Office 365, we in HDC will be moving our software develop to Visual Studio Teams Suite (VSTS).  When looking at more and more researchers moving to GitHub, Mike indicated to me that VSTS has some GitHub integration or compatibility.  We are thinking of looking into how VSTS and GitHub work together to possibly achieve some streamlining for researchers who are thinking of putting data into GitHub, and possibly, if VSTS is a more secure place to put data, and then integrate GitHub for version control for code and output.. this may be something to consider as an organization.  This is a long winded way to say when looking at GitHub training and uses, perhaps we should begin exploring how GitHub and VSTS work together (as a solution for researchers who put their (hopefully not) sensitive data into GitHub.  Sorry to steal a issue thread....Just came into my mind

**Comment by vortexing** [comment]
Addressed by a recent pull request.
