### ISSUE TITLE
How do we cite the wiki?

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#487]
For publications, who is the author, etc.

**Comment by vortexing** [comment]
In what context?  Elaborate por favor.

**Comment by vortexing** [comment]
Can we mint a DOI on a regular basis and create a contributors list to associate it with it.

**Comment by k8hertweck** [comment]
I'll write up a proposal for how we can submit to [Zenodo](https://zenodo.org) periodically to get a citable DOI.
