### ISSUE TITLE
Searching wiki through Centernet

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#492]
Since Centernet switched to Elasticsearch, it should be possible to index the wiki and make it searchable through Centernet. 

@jnooraga is keen to explore this!

Related issue: identifying whether links to CenterNet pages in the Wiki are broken (currently not possible with our existing method of link checking)
- can we modify the existing wiki tool to allow this?
- can we ask for feedback from CenterNet when folks click a broken link from the wiki domain?

**Comment by vortexing** [comment]
This is waiting on incorporation of our index into Centernet Elastic search, which depends on someone outside of the Wiki-sphere.

**Comment by vortexing** [comment]
This is so far from being possible I can't even stand to look at it.
