### ISSUE TITLE
Contributing permissions

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#498]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://github.com/FredHutch/wiki/blob/master/README.md

### Specific information requests or concerns, or specific region on page of content to refresh.
The contributing guidelines don't say that you need to be added to the repo to be able to contribute (e.g., follow the rest of the directions in the contributing guidelines.

### @ GitHub username of the listed primary reviewer of the page if known
@lakikowolfe (thanks for the heads up about this missing piece of info!)

**Comment by k8hertweck** [comment]
The clarification that should be added: Anyone who belongs to the Fred Hutch GitHub organization has the ability to write to the repo. Email SciComp to get added to the org

**Comment by vortexing** [comment]
Addressed by an accidental commit to master.
