### ISSUE TITLE
Shift fredhutch.io resources page vs training notices

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#50]
As per discussion with Kate, 
- [x] shift resources links into sciwiki, and 
- [ ] make training information feed more obviously to fredhutch.io in the training/in person pages alongside notices for office hours/consulting NOT via fredhutch.io, and
- [ ] add more text that contains the background information needed prior to signing up for a fredhutch.io class, or to read before you look at class materials.

**Comment by k8hertweck** [comment]
Currently working in branch `fhio_transfer` on this issue

**Comment by k8hertweck** [comment]
resources links included in #83
