### ISSUE TITLE
Repurposing Python User Group's: Python IDEs content for SciWiki

### ISSUE THREAD

**Issue by Chilliwack** [FredHutch/wiki#502]
**Proposed Domain**
Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.

Scientific Computing > Software Development > Python

**Content Summary**
Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded. 

Repurpose and showcase the content created by KB, ZR and JB listed here:

VSCode: https://github.com/kmayerb/visual_studio_code_demo/blob/master/README.md
PyCharm: https://github.com/zyd14/pycharm_demo/blob/master/README.md
Jupyter Lab: https://github.com/Chilliwack/jupyter_demo/blob/master/README.md

And focus on the fact that as a new user you'll want to get familiar with a debugger, variable inspector, linter, version control integration, text editor, and basic keyboard shortcuts regardless of the IDE to be effective. Open to suggestions as well on how to repurpose this content for the wiki.

**Local Content Expert(s)**
Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too).
@zyd14 @kmayerb @Chilliwack

**Comment by vortexing** [comment]
I would seriously consider just straight up adding each of these three READMEs into wiki/_compdemos/ to render in the Resource library.  Then add links to each of them form the Scientific Computing > Software Development > Python page.  I can make that happen with the correct front matter if it is unclear how to do this. ;). Just tag me.

**Comment by Chilliwack** [comment]
great idea but these are my meal ticket into the docathon so if no biggie Ill wait till then to do it :)

**Comment by vortexing** [comment]
Ah, well a better plan would be better.  I was going minimalist/low bar...

**Comment by vortexing** [comment]
NUTS!  The pycharm images are still broken on the live site.  https://sciwiki.fredhutch.org/scicomputing/software_python/#pycharm

@zyd14
