### ISSUE TITLE
Instructions for mounting drives directly to your computer.  

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#515]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
???
### Specific information requests or concerns, or specific region on page of content to refresh.
This link to Centernet 
https://centernet.fredhutch.org/cn/u/center-it/help-desk/mac-support/network_drive_paths_mac.html

### @ GitHub username of the listed primary reviewer of the page if known
??

**Comment by chrisequalsdev** [comment]
Closing as I am working on this in https://github.com/FredHutch/wiki/issues/707
