### ISSUE TITLE
Add overviews to Large Scale Data Generation

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#545]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/generation/datagen_overview/

### Specific information requests or concerns, or specific region on page of content to refresh.
We need things on the overview page for some subsections:
- flow cytometry
- imaging
- proteomics

**Comment by vortexing** [comment]
reframing
