### ISSUE TITLE
Unable to build website locally

### ISSUE THREAD

**Issue by zyd14** [FredHutch/wiki#554]
**URL of page(s) of concern**
Specify the URLs of the page(s) where there are technical problems.

https://github.com/FredHutch/wiki/blob/master/README.md

**Describe problem**

When attempting to follow the provided instructions on how to build the website locally, I ran into a few issues.  The first issue I found was that at least Ruby 2.4.0 was required in order to install `bundler` or any of the gems in the Gemfile.  To update Ruby I had to install `rvm` (I used these instructions for Mac - https://medium.com/@IanRahman/how-to-upgrade-ruby-on-a-mac-a592c6085c63), it'd probably be good to have instructions for Linux / PC too).  I then used `rvm install ruby-2.7.0` and `rvm use 2.7.0` to use the correct version of Ruby. I'm happy to add some content surrounding these steps. I also chose Ruby 2.7.0 as there are some fairly serious security patches implemented post 2.4.0.

Once I had Ruby updated a dependency conflict was discovered when running `gem install -g Gemfile` as it appears that the declared 'nokogiri' version is incompatible with other dependencies:
<img width="446" alt="Screen Shot 2020-05-14 at 10 34 16 AM" src="https://user-images.githubusercontent.com/1015576/81966680-af980a80-95ce-11ea-92ca-dedad68aae40.png">

When I comment out the `nokogiri` dependency the Gemfile installs correctly.  It seems to install `nokogiri 1.8.1` to satisfy a transitive dependency for `html-proofer` (which I think is another transitive dependency).

Now that everything seems to be installed correctly, I can execute `bundle install`, which seems to bundle all the gems correctly.  But then when I execute `bundle exec jekyll serve` I get an error which seems to come from deep in the liquid or jekyll libraries of "uninitialized constant Faraday::Error:ConnectionFailed (NameError)
Here's the end of the stack trace with the error:
<img width="1277" alt="Screen Shot 2020-05-14 at 10 56 52 AM" src="https://user-images.githubusercontent.com/1015576/81968766-b411f280-95d1-11ea-8821-cffa979d3400.png">  

Earlier in the same stack trace there is a Github API authentication error as seen here:
<img width="933" alt="Screen Shot 2020-05-14 at 10 58 25 AM" src="https://user-images.githubusercontent.com/1015576/81968928-fc311500-95d1-11ea-8fd7-856e17416f09.png">  
Could there be a Github authentication step that's missing and making me unable to access some of the required gems?

Lastly there also seems to be a failed GET request to a FredHutch wiki URL in the same stack trace, seen here:
<img width="1644" alt="Screen Shot 2020-05-14 at 10 57 06 AM" src="https://user-images.githubusercontent.com/1015576/81969106-4619fb00-95d2-11ea-9559-492f4d6976d2.png">

It may be something local to my machine but any guidance would be appreciated.

**Comment by vortexing** [comment]
I had a similar issue and my solution was to:  Just Not.  Sorry.  I went down a number of rabbit holes and never managed to come up with a working solution.

**Comment by vortexing** [comment]
Getting addressed hopefully by issue #601
