### ISSUE TITLE
Python IDEs

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#555]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/scicomputing/software_python/

### Specific information requests or concerns, or specific region on page of content to refresh.

I am so excited this page exists; I have lots of questions about interpreters in my python classes and this is a great resource.

- fix duplicate "Juyter notebook" subheadings (I think the first one should be down one more level?)
- change bottom level headers to bold, since there are so many things in the sidebar
- add a few links out to explanations for python jargon (e.g., magic sauce/beans)
- mention ssh extension for VS Code (sci comp folks use this a lot!), as well as WSL integrator to allow this to work on Windows
- add brief info about other IDEs (basic reasons why we prefer those listed)

### @ GitHub username of the listed primary reviewer of the page if known
@zyd14

**Comment by vortexing** [comment]
Reopening b/c the remaining bullets are not addressed yet.  Formatting is hard!

**Comment by zyd14** [comment]
Shoot! I'll give it another try this weekend. It should be close!

**Comment by vortexing** [comment]
@k8hertweck What do you think about finalizing this?  Are we done?

**Comment by k8hertweck** [comment]
I'll check it out tomorrow.
