### ISSUE TITLE
Add content about Globus

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#556]
**Proposed Domain**

Scientific Computing, but not sure where. I'll make a page that includes all info and we can decide if we should split it up, put it all in one place, or make it a demo.

**Content Summary**

- what is Globus?
- relationship with Galaxy
- tools available
- how to access
- integration with other Hutch resources
- where to ask for help

**Local Content Expert(s)**

I (@k8hertweck ) am the point of contact for the Hutch

**Comment by bmcgough** [comment]
I don't know much about using Globus for analysis, but I have worked with several researchers on setting up Globus Connect Personal to transfer data. I would be happy to write up some instructions on it if that would help.

**Comment by k8hertweck** [comment]
Perfect, that would be amazing. Feel free to include in this issue, send to me personally, or create a branch in this repo.

**Comment by k8hertweck** [comment]
As per convo with @vortexing :

- create resource library entry
- preface with caveat that we don't have a ready way to manage deployment for new folks
- include information about how to access
