### ISSUE TITLE
Bionic Upgrade Page Review

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#565]
> check list for all pages in scicomputing- review and create issues when a page requires updates

 - [x] access_credentials.md
 - [x] access_methods.md
 - [x] access_overview.md
 - [x] access_permissions.md
 - [x] comp_index.md
 - [x] compute_cloud.md
 - [x] compute_environments.md
 - [x] compute_gpu.md
 - [x] compute_grants.md
 - [x] compute_jobs.md
 - [x] compute_overview.md
 - [x] compute_parallel.md
 - [x] compute_platforms.md
 - [ ] compute_quickstart.md
 - [ ] compute_scientificSoftware.md
 - [ ] reference_overview.md
 - [ ] reference_training.md
 - [ ] software_examples.md
 - [ ] software_linux101.md
 - [ ] software_managecode.md
 - [ ] software_overview.md
 - [ ] software_python.md
 - [ ] software_R.md
 - [ ] software_running.md
 - [ ] software_standards.md
 - [ ] store_collaboration.md
 - [ ] store_databases.md
 - [ ] store_objectstore.md
 - [ ] store_overview.md
 - [ ] store_posix.md
 - [ ] store_scratch.md

**Comment by vortexing** [comment]
@atombaby whatcha think about this?  Feels like the rest of these would've been updated post-bionic if they'd had any issues right?
