### ISSUE TITLE
Update GPU information for Bionic Upgrade

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#567]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/compute_gpu/

### Specific information requests or concerns, or specific region on page of content to refresh.

 - update GPU type tables
 - get rid of Koshu information
 - update `sbatch` resource request requirements

**Comment by vortexing** [comment]
I'm feeling like you did this @atombaby.  Between this and the koshu/beagle PR I have, I think we can close this.  I'll leave that up to you though.
