### ISSUE TITLE
Update compute platform page for bionic

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#571]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/compute_platforms/

### Specific information requests or concerns, or specific region on page of content to refresh.

 - nomachine information needs updating for change from lynx et alia to the rhino-zero nodes
 - update node and partition information

**Comment by vortexing** [comment]
Closed by #623
