### ISSUE TITLE
Data visualization resources

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#576]
**Proposed Domain**
Scientific Computing

**Content Summary**
Information on software, approaches, and people for data visualization. Not sure where to add this, but could link to [this demo](https://sciwiki.fredhutch.org/compdemos/ucsc-track-s3/), reference the [Center for Data Viz](https://viz.fredhutch.org). I'm also creating a data viz series of classes for fredhutch.io so I'm thinking about these things a lot...

**Local Content Expert(s)**
I'm happy to add this, but welcome content and ideas from others

**Comment by ritchelong** [comment]
I'm currently working on some viz stuff involving use of plotly, pandas, and some dask for larger datasets ran locally. 

I'd love to add in some examples and tackle this w/ you.

**Comment by k8hertweck** [comment]
Awesome, @ritchelong ! I created a [branch](https://github.com/FredHutch/wiki/tree/data-viz) to hold our thoughts for now. I'm not sure where all of this content will end up but it sounds like an eventual addition of content to wiki pages and CompDemos. Off the top of my head, it would be good to have:

- a page documenting various approaches to data viz (tableau, with code, other favorite resources for creating figures)
- compdemo on applying plotly

**Comment by vortexing** [comment]
#599
