### ISSUE TITLE
Resource library entry comparing git interfaces

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#577]
**Proposed Domain**
SciComp demo

**Content Summary**
Comparison of GitHub Desktop, command line, RStudio interface, Atom, VSCode, Git Kraken

**Local Content Expert(s)**
I can do this (I basically do it in my GitHub class anyway and was getting to document it there, but figured it was better suited here)

**Comment by vortexing** [comment]
Include in #596 ????

**Comment by k8hertweck** [comment]
This was included in #596
