### ISSUE TITLE
Information on governance of this project

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#579]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
Add information in contributing guidelines

### Specific information requests or concerns, or specific region on page of content to refresh.
Add content reflecting how project is run, similar to information included [here](https://merely-useful.github.io/py-rse/py-rse-teams.html#py-rse-teams-workflow), specifically [this](https://merely-useful.github.io/py-rse/py-rse-teams.html#py-rse-teams-martha)

### @ GitHub username of the listed primary reviewer of the page if known
I can do this

**Comment by k8hertweck** [comment]
two reviews required, not all need to be from wiki-writer-editors (but one must be)

**Comment by vortexing** [comment]
Links done broke so we'll just have to do better in the future.
