### ISSUE TITLE
Creating pathways (collections of pages)

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#609]
The SciWiki is currently written like an encyclopedia. This is great for reference, but difficult for users to know where to get started when trying to learn something new. For example, the [Quick Start Guide](https://sciwiki.fredhutch.org/scicomputing/compute_quickstart/) is set up to make it easier for experienced users to get going, since they already have a basic idea of how things work and minimal information is appropriate. As the SciWiki increases in size, the search tool will vary in effectiveness, because cross referencing topics will increase the number of page hits.

I propose creating a new set of pages branded "pathways," which collect pages tagged with certain topics. Everything with a particular tag can be included in a collection (page listing the links). Each collection will include a preface at the top that includes specific references to sections of the linked pages, and orders them in a way to help walk a researcher through a new topic. Pathways can include wiki pages AND demos.

An example of how this would work is cloud computing. #597 includes links to multiple pages included in the cloud migration revamp; these pages are spread out among multiple sections, so a pathways page for cloud walks someone through gaining access, how storage works, and how to develop compute. 

Needed steps:
- identify tags to use
- apply tags
- create collections (based on tags)
- write preface to each collection that references certain sections of the linked pages, in order by utility
- document tags, collections, and pathways in README
- advertise to community
- add pathways on front page of SciWiki?

Possible tags (corresponding to a collection/pathway):
- cloud (definitely needed)
- genomics (test case for implementation, includes data generation and scientific computing)
- R at the Hutch (software dev and cluster stuff)
- Python at the Hutch (software dev and cluster stuff)
- data analysis/visualization (now I have data. what do I do?)
- workflows (Nextflow, Cromwell, parallel computing, slurm)
- HPC/large scale computing (on-premise, not cloud)
- remote computing (access recommendations)

**Comment by k8hertweck** [comment]
Looks like tags aren't going to be a feasible way to collect pages.

We can instead use the yaml-based method of creating tables used by SciComp (example [here](https://github.com/FredHutch/wiki/blob/master/_data/cluster_nodes.yaml)), which would make it easier to update links.

The pathways could be collected on a single page (markdown file), listed somewhere in resources. Each pathway also has a separate markdown file that includes explanatory text and the table. Then each pathway also has a yaml (stored in `_data/` from which the table is formatted.

Additionally, we could use pathways to create customized onboarding for each lab.

**Comment by atombaby** [comment]
I am very excited about implementing some kind of pathways concept as part of the spring cleaning I'm doing.  We've been called out a few times on the lack of documentation that provides step-by-step information for using compute resources.

I'm particularly interested in the idea of groups and labs being able to build and design their own pathways specific to the work they're doing.  That would likely include some domain-specific information TBD.

I think a couple things may be necessary to implement these in a sustainable way.  First, stable references to steps in a pathway and second, a way to be notified of or to highlight deprecated steps in that pathway.

**Comment by vortexing** [comment]
Your best bet for this is to make scicompannounce posts with names that describe who the intended pathway might before, and then put in links to the various docs they'll need.  Start there and then we can build on that.  The original idea I had that started the Wiki way back in the day was an actual decision tree/Zingtree tool.  I think given the challenges of technically doing any of the pathway ideas that have been had before seem to be where people focus first BEFORE there is actual content.  

Make the content, THEN see how we can expand upon that.

**Comment by vortexing** [comment]
This, I'm happy to say, has been solved!!!!
