### ISSUE TITLE
remove largenode references

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#613]
Which pages need this removed? (related: which pages, like "How to Gizmo", are going away?)

We should include a note that `largenode`was a previous option, in case people are confused about updating older code.

Additionally, the [examples repo](https://github.com/FredHutch/data-science-examples) needs to be updated as well.

**Comment by vortexing** [comment]
Largenode references appear to be gone.  @k8hertweck can you close this issue and create the issue to update the examples repo over in that repo?  THNX
