### ISSUE TITLE
Koshu still appears in quickstart

### ISSUE THREAD

**Issue by matsen** [FredHutch/wiki#621]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/compute_quickstart/

### Specific information requests or concerns, or specific region on page of content to refresh.

Koshu isn't around anymore, as far as I know. 

It also appears at the end of https://sciwiki.fredhutch.org/scicomputing/compute_platforms/

### @ GitHub username of the listed primary reviewer of the page if known

I didn't see one, but @atombaby certainly knows what's going on!

**Comment by vortexing** [comment]
Fixed
