### ISSUE TITLE
rModules page is out of date with new design for Fred Hutch R modules

### ISSUE THREAD

**Issue by bdconnolly** [FredHutch/wiki#622]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/rModules/

### Specific information requests or concerns, or specific region on page of content to refresh.
The information on this page is out of date. A new design for Fred Hutch R modules has been released and this page needs to be updated with new guidance.

**Comment by vortexing** [comment]
FIXED!!!!
