### ISSUE TITLE
Note we have access to Amazon Comprehend Medical

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#637]
**Proposed Domain**
Cloud computing section?

**Content Summary**
Researchers at the Hutch have access to [Amazon Comprehend Medical](https://aws.amazon.com/comprehend/medical/) at no cost through a cooperative agreement. We should at least state this is available.

**Local Content Expert(s)**
I can add this as a part of #597

**Comment by vortexing** [comment]
No longer relevant.
