### ISSUE TITLE
Transferring data

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#643]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/store_overview/#data-transfer

### Specific information requests or concerns, or specific region on page of content to refresh.

The data transfer section above only mentions Motuz, which is described as sharing data among FH storage locations. We should include notes/links to relevant demos about other recommended methods (e.g., command line), and for transferring from a local computer to storage, as well as recommended practices for command line transfer (rsync vs scp, use of login nodes, etc), and links to https://sciwiki.fredhutch.org/scicomputing/store_posix/

**Comment by k8hertweck** [comment]
HEY LOOK @vortexing I FILED THE ISSUE

**Comment by atombaby** [comment]
Superseded by https://sciwiki.fredhutch.org/scicomputing/store_collaboration/
