### ISSUE TITLE
What's the difference between grabnode and srun?

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#648]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

This page (https://sciwiki.fredhutch.org/scicomputing/compute_jobs/) describes srun as a tool for running interactive jobs, but it's not clear how this is different from grabnode.

**Comment by atombaby** [comment]
Fixed in [957e77b](https://github.com/FredHutch/wiki/commit/957e77b8fd999d48aa4a4763d76191e3ed208fa7)
