### ISSUE TITLE
Run Rstudio on HPC documentation contains out of date example

### ISSUE THREAD

**Issue by bdconnolly** [FredHutch/wiki#656]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/scicomputing/software_R/#run-rstudio-server-on-an-hpc-machine

### Specific information requests or concerns, or specific region on page of content to refresh.
The documentation states 

> Once you are on the node you grabbed, choose a version of R by using the module load command (ml for short). (Example: ml R/3.6.1-foss-2016b).

However the module referenced in the example no longer exists.  The example should be `ml R/4.0.3-foss-2020b`.

**Comment by bradleybio** [comment]
Hi Brian,

Thank you for the suggestion, but using my custom build of R is important for my current pipeline. Would you be willing to please help with determining whether there were any module changes that led to the problem with loading gfortran?

Thank you,
Rob

--
Robert K. Bradley
Professor, Public Health Sciences and Basic Sciences Divisions
McIlwain Family Endowed Chair in Data Science
Fred Hutchinson Cancer Research Center
http://bradleybiology.org/



On February 2, 2021 at 3:31:29 PM, Brian Connolly (notifications@github.com<mailto:notifications@github.com>) wrote:

URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/software_R/#run-rstudio-server-on-an-hpc-machine

Specific information requests or concerns, or specific region on page of content to refresh.

The documentation states

Once you are on the node you grabbed, choose a version of R by using the module load command (ml for short). (Example: ml R/3.6.1-foss-2016b).

However the module referenced in the example no longer exists. The example should be ml R/4.0.3-foss-2020b.

@ GitHub username of the listed primary reviewer of the page if known

**Comment by bdconnolly** [comment]
Robert, I am sorry for the confusion. This issue is about an example in this section of the wiki https://sciwiki.fredhutch.org/scicomputing/software_R/#run-rstudio-server-on-an-hpc-machine. 

Another researcher tried to follow the example and it did not work for them, which is why I opened the issue. 

About your gfortran problem; yes I can help you. I will respond on the ticket you opened yesterday.

**Comment by bradleybio** [comment]
Wonderful, thank you! I'm sorry for my confusion above.
