### ISSUE TITLE
Readme template

### ISSUE THREAD

**Issue by lakikowolfe** [FredHutch/wiki#658]
**Proposed Domain**
*Specify where should the new content should go (Data Generation or Scientific Computing), including a recommended subsection.*

- scientific computing

**Content Summary**
*Summarize the topic you'd like to be added, or include a URL with content you would like to be expanded.*

Build out a basic readme for researchers to use with datasets. Loosely based on what is covered in the [Cornell readme guide](https://data.research.cornell.edu/content/readme). Focus on paring down this guide so it is more accessible and relevant to researchers.

**Local Content Expert(s)**
_Suggest any Fred Hutch based experts who we might ask to contribute (GitHub ID is preferred, but name of someone and/or desired expertise is ok too)._

**Comment by k8hertweck** [comment]
I think maybe a CompDemo for this, too? We could include a code block that includes the README template (or make it downloadable somewhere), and then shares an example of what the template looks like when it's been filled out

**Comment by btb-hutch** [comment]
Don't hate me, but perhaps along with a readme template is some notion or suggestion about licenses and copyright?

________________________________

**Comment by k8hertweck** [comment]
@btb-hutch Of course! There's a section for information licenses and permissible use included in the Cornell template linked above, and it will certainly be one of the sections included in our tutorial.
