### ISSUE TITLE
Genomics and bioinformatics analysis types

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#661]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

Add resources explaining [types of services available from genomics/bioinformatics](https://www.fredhutch.org/en/research/shared-resources/core-facilities/genomics-bioinformatics.html). 
In particular, the [wiki genomics page](https://sciwiki.fredhutch.org/generation/datagen_platformsData/) includes information on [genomics core services](https://www.fredhutch.org/en/research/shared-resources/core-facilities/genomics-bioinformatics/genomics-services.html), like genomic platforms and some data types,
but we should include the rest present on the SR page.
Additionally, a parallel page for [bioinformatics standard services](https://www.fredhutch.org/en/research/shared-resources/core-facilities/genomics-bioinformatics/bioinformatics-services.html) would be awesome.

### Specific information requests or concerns, or specific region on page of content to refresh.

Each type of platform, data type, and analysis type should have links to additional resources. The wiki page already includes a "resources" section at the bottom, but it would be great to organize this information a bit better (e.g., what does each link provide?). Additionally, let's compile resources for each data platform/type and analysis, such as:
- video (YouTube, etc) explaining/showing technology
- primary research articles explaining technology/analysis
- blog posts, company links, etc 

### @ GitHub username of the listed primary reviewer of the page if known
@k8hertweck

**Comment by vortexing** [comment]
This is now beyond anything we can realistically make happen.
