### ISSUE TITLE
CompDemo about Seurat

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#666]
**Proposed Domain**

https://sciwiki.fredhutch.org/compdemos/

**Content Summary**

Using Seurat on gizmo

**Local Content Expert(s)**
@k8hertweck to write, reviews from @fizwit (expert) and @lakikowolfe (knows R but maybe hasn't used package, and not on cluster)

**Comment by k8hertweck** [comment]
Summary of content, for using Seurat on cluster:

- what is Seurat, why it's challenging to use locally (install is hard)
- log on to rhino
- load R and fhSeurat (explain latter and what else it includes)
- launch RStudio 
- check .libpaths
- load libraries
- achieve scientific success

**Comment by vortexing** [comment]
ain't gonna happen.
