### ISSUE TITLE
Update Centernet page for Wiki

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#689]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://centernet.fredhutch.org/cn/u/sciwiki.html

### Specific information requests or concerns, or specific region on page of content to refresh.
Add HDC domain in there plus link to HDC centernet page
https://www.fredhutch.org/en/research/shared-resources/core-facilities/hutch-data-core.html

### @ GitHub username of the listed primary reviewer of the page if known
@vortexing

**Comment by monicagerber** [comment]
this looks done. ok to close @vortexing ?
