### ISSUE TITLE
How to map drives to local computer

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#707]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
Not sure exactly where this should live.   Maybe it already does live somewhere and I can't find it. 

### Specific information requests or concerns, or specific region on page of content to refresh.
How (and maybe when) one can map their home or other locations on scratch or fast to their local computer.  Perhaps noting that large transfers shouldn't be done this way?

**Comment by chrisequalsdev** [comment]
Grand idea, working on this now.
