### ISSUE TITLE
Update jupyterlab instructions

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#724]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/software_python/#jupyter-notebooks-on-rhino

### Specific information requests or concerns, or specific region on page of content to refresh.

Doesn't reference the jupyterlab modules.  Also references `grabjuypter` which is no more

**Comment by vortexing** [comment]
@atombaby this seems fixed to me.  There is no `grabjuypter` in the branch for my big PR right now.

**Comment by atombaby** [comment]
That's half of it, but I think we're still supporting jupyterlab via grabnode/ml jupyterlab/.... and that's the instructions we're missing.

**Comment by vortexing** [comment]
Got it.  ok.  Then I'll leave this alone since I can't help with that.  thanks!

**Comment by chrisequalsdev** [comment]
I updated this section last week to document the difference and use of both Jupyter lab & notebook.
