### ISSUE TITLE
Update contribution instructions 

### ISSUE THREAD

**Issue by k8hertweck** [FredHutch/wiki#73]
Prior to going "live" in September and (hopefully!) receiving more contributions from the community, we should revisit the instructions for editing in both the README and the "About the wiki" page, making sure these are updated and consistent with each other. Rather than duplicating text, it might be better to leave only one copy of instructions for contributing in the README and simply put a link in the rendered page directing folks there.

**Comment by vortexing** [comment]
I took a moment to update the readme and the public facing instructions to be an intermediate, which I think is only FINE, but not great.  I will leave this issue open so I come back and update the setup later to make it all grown up later.
