### ISSUE TITLE
Add dmptool links

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#733]
**Proposed Domain**

Data generation

**Content Summary**

Add a link and description for https://dmptool.org/

> The DMPTool is a free, open-source, online application that helps researchers create data management plans (DMPs). These plans are now required by many funding agencies as part of the grant proposal submission process. The DMPTool provides a click-through wizard for creating a DMP that complies with funder requirements. It also has direct links to funder websites, help text for answering questions, and data management best practices resources.

**Local Content Expert(s)**

**Comment by atombaby** [comment]
Future work may include adding hints specific for our organization

**Comment by vortexing** [comment]
This should go into data science as we re-envision data generation guidance.
