### ISSUE TITLE
Integrate Beagle instructions

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#74]
@TapscottLab has this markdown containing the basics of Beagle:
https://github.com/FredHutch/FHBig/blob/gh-pages/_posts/2018-04-04-Beagle-Quick-Start.md

Also, I'm off campus and too lazy to VPN in, so I can't see the content at the old scicmp wiki she linked to.  Can we incorporate that?  

Can we move it all into the Wiki somewhere?  Either in the compdemos Resource library as a how-to, OR into a page on cloud HPC in the Computing/Resource section?  Then we can add other cloud computing things there too as they become relevant/possible?

**Comment by vortexing** [comment]
@atombaby You're Beagle right?  Think you can figure out how to build up a Beagle section in http://sciwiki.fredhutch.org/computing/cluster_rhinoGizmo/ ?  

We'd talked about whether to divide by cloud v on-prem, or not and decision was just Beagle as an extension to rhino that just happens to be cloud based.  How do you want that page to look?  Or, @bmcgough should we have a Rhino on-ramp page and then this gizmo/beagle type page, and then any cloud-y things like globus be on the cloud page? 

Thoughts?

**Comment by atombaby** [comment]
In https://github.com/FredHutch/wiki/pull/81
