### ISSUE TITLE
Storing AWS credentials for CLI use

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#751]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/access_credentials/#amazon-web-services-aws

### Specific information requests or concerns, or specific region on page of content to refresh.

Storing AWS credentials is not documented here.  It was handled in the `awscreds` command, but that no longer applies with the new account setup.

Material would look something like https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by chrisequalsdev** [comment]
https://github.com/FredHutch/wiki/pull/775

**Comment by chrisequalsdev** [comment]
Closing as this was resolved in #775
