### ISSUE TITLE
Conducting User Experience Testing

### ISSUE THREAD

**Issue by cansavvy** [FredHutch/wiki#759]
When it is deemed appropriate, it would be great to conduct some user testing on SciWiki to find out where it might improve. As I learn more about SciWiki, I might come back to this issue to further polish this and hone in on these objectives. 

Before we can find out how SciWiki can improve, we need to more clearly state its goals. 

Based on what I understand, its goals are _to provide scientific data knowledge and resources to those who are looking for it._ 

**Some starter questions we may want to answer using user experience testing:** 
1) Who are SciWiki's users? - This influences how these articles should be written and what resources should be referred to. 
2) Navigability - how well can users find what they are looking for? How do they generally use the SciWiki navigation items and functions? i.e. are they mostly using the search function, the sidebar, something else entirely? 
3) Clarity - What makes some articles clearer or not so clear than others? What information could be added (or subtracted) to make the information more clearly understood by SciWiki's user base?

**Comment by monicagerber** [comment]
Could be a future HCI project when/if they want to do this, but not an acute issue that needs addressing right now.
