### ISSUE TITLE
Automagic Easybuild docs

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#762]
In reference to our easybuild docs convo, I'm wondering if @dtenenba might have ideas as to how best to integrate a copy of markdowns from the easybuild repo into this repo upon PR merge into master and build.  

As an example, this could be a GitHub Action but maybe makes more sense to occur IN our build process?  
https://stackoverflow.com/questions/59408320/github-action-to-copy-a-file-from-one-repo-to-another

What needs to happen is this:
```
git clone https://github.com/FredHutch/easybuild-life-sciences.git easybuild
cp easybuild/docs/_r wiki/_rModules
cp easybuild/docs/_python wiki/_pythonModules
```
Then all the markdown posts in the easybuild module at Wiki build time will then be available in the two module folders here so they will be rendered on the site (and searchable here).

**Comment by dtenenba** [comment]
This is certainly doable and seems easy enough. And Gitlab seems like the right place to do it - there is no need to have multiple, possibly conflicting CI/CD processes.

The one thing I am not clear about is how you get to these files from elsewhere in the wiki. Sure, you can search them, but should we generate index pages (one for R, one for Python)  that has links to each of these markdowns? And then have that linked to somewhere else in the wiki? So you can find stuff w/o searching?

**Comment by vortexing** [comment]
WE have those index pages already.

**Comment by vortexing** [comment]
Main software page:
https://sciwiki.fredhutch.org/scicomputing/compute_scientificSoftware/

Then R page:
https://sciwiki.fredhutch.org/rModules/
Then python page:
https://sciwiki.fredhutch.org/pythonModules/
