### ISSUE TITLE
Clarify documentation of cluster software modules

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#766]
We got John's cluster module documentation into the Wiki in an automated fashion.  BUT that means currently that allll R and python modules are documented on the wiki.  Do you all want that?  Should we just put in the fhX modules?  Should we preface the R adn python module lists with a blurb that explains what the fh's are vs the bald modules?

**Comment by fizwit** [comment]
The modules listed in fhR contain all the modules in the base R. The R module list is duplicated in fhR. But many people only use R and not fhR.  It is worth keeping R and fhR because the usage is almost split.

I am adding a description of the `fh` modules in the branch `modules.`
