### ISSUE TITLE
update mountain/cyberduck page to work with S3 not swift

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#774]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/compdemos/Mountain-CyberDuck/

### Specific information requests or concerns, or specific region on page of content to refresh.

Update this to replace economy local (swift) with economy cloud (S3).

**Comment by vortexing** [comment]
duplicate of #758
