### ISSUE TITLE
Need a method to find orphan pages

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#785]
If PR #784 is merged then we will need a new way to find orphan pages.
Actually, the old way did not notify us about orphan pages, it just made sure they were not indexed into the Elasticsearch index.
So we need something like [this](https://github.com/MOLOCH-dev/jekyll-orphan-pages-action/blob/main/action.yml) running in GitLab, as a Lambda, or as a cron job. 

Note that this is separate from the logic in gitlab that finds orphan assets (images, css, etc). 
What I am talking about here is finding orphan HTML pages.

**Comment by vortexing** [comment]
Done!
