### ISSUE TITLE
Data rentention policies for various data storage locations

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#786]
Sometimes when people get DUA's negotiated there are stipulations about data retention, which has implications for backup systems.  

Could we capture some degree of how long data is retained in backups depending on where it is stored using Hutch IT supported systems?

**Comment by atombaby** [comment]
I believe that the information [here](https://sciwiki.fredhutch.org/scicomputing/store_overview/#allocations-and-costs) covers most of it.  There are some corrections necessary (notably to the cost structure) which I think will complete this.
