### ISSUE TITLE
broken link on Quick Start page

### ISSUE THREAD

**Issue by TrofimovAssya** [FredHutch/wiki#787]
Hi!

I found some issues on page:
**[URL of page(s) of concern](https://sciwiki.fredhutch.org/pathways/path-batch-computing/)**

There are broken links when clicking on the words [connect to the login nodes known as rhino.](https://sciwiki.fredhutch.org/pathways/path-batch-computing/scicomputing/access_methods/#ssh-connections)

as well as  

[SLURM works](https://sciwiki.fredhutch.org/pathways/path-batch-computing/scicomputing/compute_jobs/#basic-slurm-terminology).

Thanks in advance

**Comment by atombaby** [comment]
Thanks- actually a few of the links in there were incorrectly written causing the broken URL in the rendered pages.  I've got the fix queued up, should [have that done RSN](https://github.com/FredHutch/wiki/pull/788).
