### ISSUE TITLE
scicomp centernet updates

### ISSUE THREAD

**Issue by atombaby** [FredHutch/wiki#794]
https://centernet.fredhutch.org/cn/u/center-it/scicomp.html

 - remove pages and references from old, shared resources vintage, data core functions (e.g. https://centernet.fredhutch.org/cn/u/center-it/scicomp/data-resource.html)
 - update information about S3, trim out overly detailed descriptions
 - remove references to economy local
 - validate links to sciwiki

**Comment by jnyhuis** [comment]
done
