### ISSUE TITLE
AWS S3 Bucket regions?

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#839]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/scicomputing/store_objectstore/#faq

### Specific information requests or concerns, or specific region on page of content to refresh.
My brain is fuzzy but I think the section on Bucket Regions should be updated to reflect our current hopes and dreams for that?   

### @ GitHub username of the listed primary reviewer of the page if known
@staciefase

**Comment by jnyhuis** [comment]
Emailed Stacey for an up-to-date list.

**Comment by jnyhuis** [comment]
-----Original Message-----
From: Mahuna, Stacey E <smahuna@fredhutch.org> 
Sent: Friday, April 07, 2023 11:18 AM
To: Nyhuis, John <jnyhuis@fredhutch.org>
Subject: Re: Q: Acceptable AWS regions

us-east-1, us-west-2, and eu-west-2 are the only 3. thanks!


Stacey Mahuna

Pronouns: she/her/hers
IT Cloud Engineering Manager
Fred Hutchinson Cancer Center
M 425.761.9813
[smahuna@fredhutch.org](mailto:smahuna@fredhutch.org)
