### ISSUE TITLE
Intro to Rhino/Gizmo

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#86]
We need an introduction to using Rhino and Gizmo to be put here:
http://sciwiki.fredhutch.org/computing/cluster_rhinoGizmo/

The old material is lost/old/might be quicker to just start from scratch.

**Comment by atombaby** [comment]
What would you think about linking to the [Software Carpentries shell novice lesson](http://swcarpentry.github.io/shell-novice/) for basic shell use and develop more Hutch specific introductory lessons like navigating the file systems, ssh access to hosts, and basic job submission/grabnode use?

**Comment by vortexing** [comment]
I very much like that idea.  I know @k8hertweck was going to link to the Carpentries as a resource for training and I believe those links went in in her last pull request.  I feel like since we all have our ACTUAL jobs, we certainly don't need to reinvent the wheel here, so linking out to useful learning material is definitely in our best interest as well for our own time management.  

I think on the researcher side, especially for people whose expertise is not in software, it is hard to know beyond just googling things where to look for help.  Links like this are great, and then summarizing in the body of the article is a good focus.

I think then moving forward our goal will be to keep trying and updating links over time to make sure we're not linking out to dead things.

**Comment by atombaby** [comment]
@vortexing I think this is fixed as of commit 3439189d8a961a2d22ec0e7293a7dd01ca2ddaf7 in `cluster_rhinoGizmo.md` and 823b97104d176a3aff997a9072fae4e33f2043dd in `linux_linux101.md`

**Comment by vortexing** [comment]
Yup, this was done and I never closed the issue!
