### ISSUE TITLE
JupyterLab instructions not working

### ISSUE THREAD

**Issue by dtenenba** [FredHutch/wiki#918]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)

https://sciwiki.fredhutch.org/scicomputing/software_python/#using-jupyter-on-rhino

### Specific information requests or concerns, or specific region on page of content to refresh.

See https://fredhutch.happyfox.com/staff/ticket/12282 

User followed instructions saying to `ml JupyterLab` but could not import numpy and matplotlib in the resulting notebook. 

Loading `JupyterLab/2.2.5-foss-2020a-Python-3.8.2` instead provides these packages.

I know these docs were updated recently (by me) and everything was tested then, but it is no longer working. 

So either we need to fix the JupyterLab module so that it works as advertised, or change the documentation. I would prefer that the `JupyterLab` module would just work so that we don't have to reference a specific version in the wiki.

### @ GitHub username of the listed primary reviewer of the page if known

@dtenenba @fizwit

**Comment by atombaby** [comment]
Updates in #923

**Comment by dtenenba** [comment]
Fixed in #964 

Can I get a donut hole?
