### ISSUE TITLE
Update fhcrc to fredhutch?

### ISSUE THREAD

**Issue by sckott** [FredHutch/wiki#924]
Via slack question and answer channel a user noticed that the connection to https://mydb.fhcrc.org/login is not secure. It appears there is a bad or missing SSL cert for that. 

fhcrc.org redirects to fredhutch.org, so should we switch all instances of fhcrc.org to fredhutch.org? Or do we only need a fix to the SSL cert in question, and leave the docs unchanged?

**Comment by atombaby** [comment]
Fixed in #926
