### ISSUE TITLE
Update Fred Hutch Oriented DaSL Training

### ISSUE THREAD

**Issue by abbywall** [FredHutch/wiki#949]
### URL of existing content (a rendered, sciwiki.fredhutch.org link)
https://sciwiki.fredhutch.org/datascience/hutch_courses/

### Specific information requests or concerns, or specific region on page of content to refresh.
Update the content for WDL 101 guide to reflect the new training materials for Developing WDL Workflows: https://hutchdatascience.org/WDL_Workflows_Guide/

**Comment by laderast** [comment]
I have updated the wiki links to point to the new WDL101 book: https://github.com/FredHutch/wiki/pull/951
