### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by jayoung** [FredHutch/wiki#975]
**URL of page(s) of concern**

https://sciwiki.fredhutch.org/scicomputing/store_posix/

**Describe the problem**
this link (bottom of the page) takes me to 'page not found' :  
[Network Drive Paths - Mac](https://centernet.fredhutch.org/u/it/help-desk/mac-support/network-drive-paths-mac.html)

**Comment by laderast** [comment]
Addressed in PR: https://github.com/FredHutch/wiki/pull/976

**Comment by jayoung** [comment]
thanks!
