### ISSUE TITLE
Wiki builds locally but automated build is not working

### ISSUE THREAD

**Issue by vortexing** [FredHutch/wiki#985]
**Describe the problem**

Looks like the last PR was merged but the edits are not showing up on the public website.  @seankross did build it locally and the edits show up there.  

https://github.com/FredHutch/wiki/pull/984

Think anyone can find the hiccup in the build?

**Comment by dtenenba** [comment]
All of the builds succeeded. So I don't know what is up. Running the build again manually.
Looks like now it shows the correct thing:

https://sciwiki.fredhutch.org/info.txt

```
Information
Branch: main
Commit: 541b4b1877612684a385cbfc97502e01a01257ce
Commit comment:
 Merge pull request #984 from FredHutch/prep-clean-generation

quite the overhaul.
Build time: Sat May 18 00:13:44 UTC 2024
```
