### ISSUE TITLE
Broken link to "pathways" 

### ISSUE THREAD

**Issue by sitapriyamoorthi** [FredHutch/wiki#996]
**URL of page(s) of concern**
[Specify the URLs of the page(s) where there are technical problems.](https://github.com/FredHutch/wiki/blob/main/pathways)

**Describe the problem**
On the main SciWiki Readme the link to Pathways is broken

**Comment by mxsmi** [comment]
I submitted a fix for this for review. Here is the link https://github.com/FredHutch/wiki/pull/1003

**Comment by tefirman** [comment]
Fixed via #1006. Thanks @mxsmi!
